### ISSUE TITLE
F8 shortcut key doesn't work anymore...

### ISSUE THREAD

**Issue by SlyRaider** [Woundorf/foxreplace#167]
Hello all,

I hope I write in a good place.

I use FoxReplace on Firefox for months, but since a week (W8.1 > W10), I can't use anymore the F8 key to replace words quickly. Can you help me? I have a website and I often used this shortcut to do a fast replacement (with a bar like CTRL+F function). Without this F8 shortcut, FoxReplace is useless for me...

How can I refind this shortcut key?

Sylvester

**Comment by Woundorf** [comment]
Hi @SlyRaider, in the latest version (0.17.0) the shortcut is now F9.

Previously it was F8 to show the bar and Shift+F8 to apply the substitution lists, but since Shift+F8 is now used by Firefox I changed them to F9 and Shift+F9 respectively.

**Comment by SlyRaider** [comment]
Hi @Woundorf : Indeed, it was so easy actually... thank you for your help!! =)
