### ISSUE TITLE
Can you help with regex?

### ISSUE THREAD

**Issue by dandidondi** [Woundorf/foxreplace#168]
I want to change codes in this pattern:
`<span class="postfilename" title="a_very_long_filename.jpg">a_very_long_fil….jpg</span>`

to this:
`<span class="postfilename">a_very_long_filename.jpg</span>`

**Comment by Woundorf** [comment]
For example, you can try with `<span class="postfilename" title="(.*)">.*</span>` as input and `<span class="postfilename">$1</span>` as output. You'll have to adjust some things if you want to make it more general, but for this simple example it works.
