### ISSUE TITLE
OK & More info button not working in Firefox Developer edition

### ISSUE THREAD

**Issue by kang21** [Woundorf/foxreplace#169]
Hello ,
can you please solve this problem. Everything except OK & More info button are working in firefox Developer edition

**Comment by Woundorf** [comment]
I see. I want to release a bugfix version soon (next week if possible). In the meantime, as a workaround, if you need to save changes you can set `browser.preferences.instantApply` to `true` in `about:config` and then changes are saved instantly.

**Comment by kang21** [comment]
thanks
