### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by reddit-is-fun** [Woundorf/foxreplace#170]
Does FoxReplace support wildcards? As an example, I want to block all words starting with "cat" ("cats", "catalog", "catapult" etc.). I don't want this to affect words containing the string "cat" though, for example "Giovanni Boccati".
I've tried "cat*" filter, it doesn't work and only filters the exact phrase.

**Comment by Woundorf** [comment]
FoxReplace supports regular expressions. If you click on the 'T' button to the left of the Replace field you can select "Regular expression" and then use __\bcat.*\b__ to match words beginning with "cat". You can learn more about regular expression syntax [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Special_characters_meaning_in_regular_expressions).

**Comment by reddit-is-fun** [comment]
@Woundorf Thanks, no experience with regular expressions. I just replace **cat** in **\bcat.*\b**.
I'm not sure if wildcard support would be a major improvement, if the feature is hard to implement there's no need to.
Please add info about regular expressions to the readme (link this thread?) and everything's fine :)

**Comment by Woundorf** [comment]
It wouldn't be that hard, but since regular expressions are already more powerful I don't see the real need.

And the link I gave you is in fact in the FoxReplace help, but maybe I could add also a little wiki here to explain this kind of things.

**Comment by reddit-is-fun** [comment]
@Woundorf To be exact, **\bexample.*\b** changes everything following the example phrase, I wondered why whole sentences were missing. I want to only change the appearance of certain word, so I removed "*" (**\bexample.\b**) from regular expression.  
Thank you for the help.

**Comment by Woundorf** [comment]
@reddit-is-fun I received a notification of another comment, but it looks like you deleted it. I replied the first time without actually checking if the regular expression worked, but now I see that it doesn't. The one that actually works is __\bcat\w*__ for the basic English alphabet, or, if you need to include letter variations, then something like __\bcat[\wàéèíïóòúüç·]*__ (add the letter variations that you need). Although __\w__ includes letters from A to Z and numbers, so if you want you avoid numbers you should use __\bcat[a-z]*__ or __\bcat[a-zàéèíïóòúüç·]*__ instead.

**Comment by reddit-is-fun** [comment]
I accidentally delete my comment, thank you.

**Comment by reddit-is-fun** [comment]
I'd like to know how much work implementing wildcards requires, would make at least my life much more easier. I'll consider a donation if  you get this done.

**Comment by Woundorf** [comment]
Maybe not a lot of work: I would have to add a new input type that is "wildcards" in addition to the current "text", "whole words" and "regular expression" and then internally convert it to the appropriate regular expression. The real issue is to decide what wildcards should be supported and what exact meaning should they have (i.e. should * match any character? or only letters? or letters and numbers? or also some symbols? or anything except spacing characters? etc.).
