### ISSUE TITLE
In the file list, give option for "RELOAD" of the same file

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#171]
We can list out several independent files in fr option window and activate/ deactivate which one to work/ not to work with.

however, if we change a file's content on the disk, we have to "clear" and then "import" afresh. 
In that also, it doesn't even remember the folder from which we had read the file last time, 
and it doesn't remember the file name also.

If those two things could be added and stored in fr, it would save on our time and efforts that we spend on locating the folder and file name for importing.

So, please, consider devising some method, so that we get a "reload" button in main window, that would CLEAR the existing file selection on which we are, and then automatically read that file from the disk, from where it had read that previous time when we had imported it.

Thanks.

**Comment by Woundorf** [comment]
You can use the subscription feature to subscribe to the local file. You just have to use a file:/// URL. You can find the URL of your file if you drag and drop the file into Firefox and then copy the URL from the location bar.

On the other hand, the location from where you import is remembered usually, but not the file name.

**Comment by vsrawat** [comment]
hi,
I tried giving a file:// type of url into import file name, 
but it is saying "only http:// type of files names permitted."

so it will not go to load a file from our hard disk.

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment]
That is only said when you import from URL, but for the subscription field the file:/// URL is supported.

**Comment by vsrawat** [comment]
It seems to elude me.

1. When I said "import from URL", it said "only http urls permitted" and didn't accept file:/// type.

2. When I select "periodically update from url" in the main window of fr, it is taking only one url (though, indeed taking file:./// url). So if I have many different and separate tables that I use for fr of different type of text, only one url is not good for all of them. it should have stored different url to update from for each table.

3. When I click EDIT in the main window and enter a URL, it is accepting file:/// url, but it is not clear when and how it is updating from that? There is no UPDATE NOW button.
here, if I don't enter a url in "periodically update from url", it is shown as "Disabled."

so, I guess the system needs fine tuning to be used for multiple different substitution tables.

Also, entering a file:/// url in "periodically update from url" and giving an UPDATE NOW button will be helpful. Though I guess selecting a 1 second update interval will also do that, but then we have to untick that or change the interval after one update, otherwise it will keep on update ad infinitum.

so an UPDATE NOW button somewhere will be helpful.
--

For that matter, may be you can give a thought to devising some method, that it does stores hdd/ http address of each substitution table, 
and also store the last updated date and time,
and when we go to actually fr, it may automatically check the current file and if the date and time of the file is later than the stored date and time of last update, that mean the file has changed, so it can message us something like "the source substitution table might have changed, update now?"

:-) getting complex...
Thanks.

**Comment by Woundorf** [comment]
1. Correct.
2. You should be able to create a single file with everything you need. That's what substitution groups are for.
3. The URLs here are to filter to which pages the substitutions are applied, e.g. if you put example.com then the substitutions in that group will be applied only to example.com.

The "periodically update from URL" part is intended for when you have a file, local or in a server, that you update somehow and then you want to import periodically to overwrite your substitution list each time. It only accepts one file because it's enough (FoxReplace stores everything in one file internally, exactly like the one you obtain when you export it).

I see that you are the same that generates a JSON file from an Excel file. I'm not an expert in Excel, but I'm very confident that it would be possible to generate the JSON for several groups instead of just one, so you would need only one file.

**Comment by vsrawat** [comment]
yes, I generate json files from Excel.

But most of the files are so huge (some having 10,000+ substitutions) that combining them would make excel very slow and shall defeat the purpose.

that is why I am also the same one who had suggested to give option to load csv files having 4-5-6 columns of plain data to fr, instead of cumbersome and strict format of json files.

Thanks.

**Comment by vsrawat** [comment]
btw, reload will be possible if fr saves the hdd location of each file, then it can just reload the file of the same name from that location.

This would have spared us using browse, then browsing to the folder in hdd, and selecting file.

But, let alone saving each files full path, fr doesn't even save the previous folder on hdd, so we have to select that manually after "Browse" because firefox resets previous folder on each restart.

Thanks.

**Comment by Woundorf** [comment]
Firefox doesn't allow me to remember the file name for security reasons, but the directory is remembered in my case. On which platform are you?
