### ISSUE TITLE
for long text, it should show "processing/ completed" type of message 

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#174]
when we change long text, it just works silently.

We don't come to know whether it has started processing or not, whether it is still processing or when it has finished.

We come to know of that by seeing whether anything is changing on screen, that indicates it has finished. but if there are small changes, or no changes, that would appear on the current window, we don't come to know.

so, please consider giving some message window or status bar message saying "processing/ completed."

thanks.

**Comment by Woundorf** [comment]
It's intended to be transparent to the user, so this definitely won't be done.

**Comment by brunolopes96** [comment]
Maybe add an option for such message to be shown? Because it would be very useful and informative for long lists on long pages.

**Comment by vsrawat** [comment]
yes, I also find requirement of some message telling the status, and 
some alarm when it has completed.

Users who don't want these can be given option not to show these.
