### ISSUE TITLE
Query: does fr keep all json files always loaded in ff memory

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#176]
I have 3 regular set of fr json files which are 49kb, 449 kb and 78 kb.

I always keep these three files loaded and switch between them (tick/ untick to activate/ deactivate) whenever such relevant work needs to be done.

I got a thought whether FR is keeping all these three files always loaded in memory of FF, that would block a chunk of my RAM always. If so, I should remove all three files from fr, and load them as and when I need to use them and then delete them from fr after using.

So, please share with us whether fr keeps all .json files always loaded in ff memory,
or does it keep them in disk profile, and reads them when we activate fr, and then again removes them from ff memory after completion of the work?
## Thanks.

Rawat

**Comment by Woundorf** [comment]
What is kept in memory is not the JSON itself, but an object structure representing the substitution lists. In other words, the information is kept in memory, but not the textual representation in JSON.

**Comment by vsrawat** [comment]
I recently observed that fr is indeed keeping a file list.json in the folder Profiles\ffprofile2\foxreplace folder.

I don't know whether it keeps separate .json files stored there for all separate "apended" lists.

If so, maybe some method could be helpful that would let FR purge its memory so that all those "object structure representing the substitution lists" is removed from its (ff's) memory and we get more memory to use.

Also, when the list.json file is present in the specified location, whenever needed fr can read the file from this location and recreate the "object structure" to do the substituion, without needing any user interference.

Also, often we know that we have not made any changes in the .json file since our last load in fr, so when fr asks users to upload json file, it can take the user to this folder itself, so that we can load the file from here itself, even if had manually deleted that from fr window.

For that reason, if FR presents different json files in this default folder itself, we can make this folder itself as our working folder for json files. or can ourselves manually move the modified json file from other location to this location so that fr can directly read it.

this way, FR will will become very trim on system resources.

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment]
The file list.json in the profile folder is where FoxReplace stores the list you see in the options window. It's read at the start and its written every time that the list is modified. You should not edit this file directly, although if you do the changes will effectively be read by FoxReplace the next time Firefox is started. But this file and the folder where it's contained are private data of FoxReplace and can change anytime without warn, and very likely will change when its' ported to WebExtensions. So this can't be your "working folder".

The object structure is kept in memory to have immediate access to it. Accessing the disk to read the file and processing its contents each time would be prohibitively slow.

But I don't get the worry for a few KB of memory.

**Comment by vsrawat** [comment]
Just one more related query:

I have 3 json files, loaded in fr in ff, which act independently, I make one of them active whichever I require.

In such a case, when you are having a single list.json file, does it have only the currently active object structure, or does it have all (for me) three object structures with one file and you are using some method to identify them separately when I switch between three .json files already loaded, because I have noticed that I don't need to load files from disk while switching the active file.

**Comment by vsrawat** [comment]
Whether quick access/ conversion is required or not, that a user can decide. 

Some users might be using fr on every page load, they require quick access.

Some others like me that don't use fr for converting web pages, but are converting our own google translation output to a more legible and meaning format of target language, we don't require quick access and we use fr, say, about 4 times a day.

my biggest .json file is half MB in text format, I don't know how much memory that would require when converted to object structures.

My pc is 8 years old, having an integrated intel graphics card for which driver updates are not getting released anymore. firefox has expressed its inability to clearn video memory from graphics card for some reason. so my ff soon occupies 1.5 GB to 2GB out of my 3.3 GB within half an hour of start. I have to close it and rerun it to reduce memory load. Hence, memory saving is required for many users for many reasons.

It should be the first thought of every software developer and every firefox/ extension developer not to use any single bit more than what is required.

**Comment by Woundorf** [comment]
When you say 3 files loaded you mean that you import three files and you choose append instead of overwrite, so that you have 3 items (groups) in the main list in the options window? If that's it then the list.json file contains all 3 of them, and when you enable or disable a group this is also stored in the file.

Don't worry about memory usage of FoxReplace with those small files. You can use [this addon](https://addons.mozilla.org/en-US/firefox/addon/about-addons-memory-2016/?src=ss) if you want to know the used memory, but it should not be too high.

> It should be the first thought of every software developer and every firefox/ extension developer not to use any single bit more than what is required.

The first goal must be that the program is correct, and the second that it's maintainable. Afterwards, it's important to not *waste* memory, but not reduce it more than necessary at the expense of more important things.

**Comment by vsrawat** [comment]
wow. that would be a boon.

first, please forgive me to make this issues thread a personal chat between us.

But I guess this outcome is a god sent one for people like me.

You are having a format in list.json in which you have kept all out json files combined.
Even if you are internally able to separate them all to different individual set of entries, so that they appear as list of 3-4 or many different json files in fr window.

Please tell us that method.

This would help thousands of your users who are keeping several different json files for each set of replacement entries which are to be used one at a time.

Hope you would see how much it would help us. It would save us from housekeeping and maintaining many different excel/ csv files or worksheets, and several different json files (extracted from excel/ csv files)

Please do consider.

Thanks.

**Comment by Woundorf** [comment]
Sorry for not responding before. What you call "many different json files in fr window" are in fact substitution groups, which consist of a list of substitutions and a list of URLs where they should be applied or not. When you import a file and choose to append it to the list, the only thing that is done is copying the groups from the imported file to the local list, and then the result is saved in that private file.

If you want to externally combine several files into one, there's no secret, you just have to put each group as an item in the "groups" array of the JSON:

```
{
  "version": "0.15",
  "groups": [
    {
      "name": "...",
      "urls": [...],
      "substitutions": [...],
      ...
    },
    {...},
    ...
  ]
}
```

Export your current list to a file to see exactly how it should look.
