### ISSUE TITLE
Not working for combining 2-line, pls help.

### ISSUE THREAD

**Issue by mbmalone** [Woundorf/foxreplace#178]
Example.
Notepad++ detects the first line end with CR LF
The Question Mark is Code "&#63;"

I tried various combos with /n but couldn't get anything to work.

Site: https://www.mediafire.com
Sharecode[?]: /download/e8627q91qm987k3/testfile.rar

Desired Result.
Site: https://www.mediafire.com/download/e8627q91qm987k3/testfile.rar

**Comment by Woundorf** [comment]
Hi, sorry for the late response. Can you explain better what are you trying to achieve and what have you tried that is not working?

**Comment by SaltatorMortis** [comment]
Site: (https?:\/\/.*)[\s\S]*Sharecode\[[\s\S]*\]: (\/([A-z0-9\-\%]+\/)*[A-z0-9\-\%]+\.\w+)
with $1$2

**Comment by Woundorf** [comment]
Ok, probably they are two different elements in HTML, separated by either ```</p><p>``` or ```<br/>```. You should look what it actually is and use HTML input & output and take this into account.

**Comment by SaltatorMortis** [comment]
true ive forgot this with my .* this code is better:
`Site: (https?:\/\/\.*?./w+)[\s\S]*?Sharecode\[[\s\S]*?\]: (\/([A-z0-9\-\%]+\/)*[A-z0-9\-\%]+\.\w+)`
with this any <> after this url will be catched with the [\s\S]*?
but it still need the http or https but you can swithc this with any url catching code you can find online
