### ISSUE TITLE
Auto-replace not replacing every instance

### ISSUE THREAD

**Issue by phineasfrogg** [Woundorf/foxreplace#179]
I've found that in the most recent versions of Firefox, the text replacement has changed *most* instances of a string of text, but there is often one or two instances left that haven't been changed, and I have to replace it again using the context menu. I've been using this extension for three years and have only started noticing these problems over the past month or so.

**Comment by Woundorf** [comment]
Hi, sorry for the late response. Can you give a specific example?

**Comment by phineasfrogg** [comment]
For example, if I were to replace 'caterpillar' with 'grasshopper' (just a frivolous example), most instances of 'caterpillar' would be changed to 'grasshopper', but there would still be some text saying 'caterpillar' until I chose 'replace with substitution list' again. In the past, all of them would have been changed to 'grasshopper' without having to replace the text again on a page that had already been rendered.

**Comment by Woundorf** [comment]
If this happens in pages with dynamically loaded content then it's an already known issue (and hard to solve), but if it happens in a more traditional page then it's another problem and shouldn't happen.

**Comment by phineasfrogg** [comment]
It's definitely happening on traditional HTML pages, not just dynamically loading content. There were a few people commenting on the Firefox extension page that had a similar problem, apparently.

**Comment by Woundorf** [comment]
Then I need a specific example (a page and a substitution) to test it myself, because I haven't encountered this problem yet.

**Comment by phineasfrogg** [comment]
I have a filter set up to convert US spellings into British ones. For example, 'colour' should always be written with a U. However, a U-less version of 'colour' slipped through on this traditional page and I had to re-run the substitution to have it changed. 
  
http://superuser.com/questions/486139/microsoft-word-strict-inforcement-of-new-zealand-british-english

**Comment by Woundorf** [comment]
I have tried it several times but can't reproduce it.

**Comment by Woundorf** [comment]
I'm now thinking that this may happen with Firefox 49 or higher, because of a change they made. I will fix it for the next release.
