### ISSUE TITLE
Foxreplace substitutions now case-sensitive, despite not being marked that way.

### ISSUE THREAD

**Issue by billybiscuits** [Woundorf/foxreplace#181]
Earlier today, Firefox updated itself, and now Foxreplace is only making substitutions if they match the case of my input. In the setting, the box for "match case" is not checked.

For an example, let's say I wanted to remove all instances of the word "cheese." If I come across "cheese," it will be removed, but if I come across "Cheese," "cHeese," chEEsE," etc, it stays that way.

I now find myself annoyed at the tidal wave of capitalized profanity flooding my browser.

**Comment by Woundorf** [comment]
This is due to a change in Firefox 49. I'll fix it as soon as possible.

**Comment by billybiscuits** [comment]
Okay. Thank you.

**Comment by Woundorf** [comment]
Fixed in e480fe0.
