### ISSUE TITLE
When might Mozilla approve 17.3?

### ISSUE THREAD

**Issue by MarkMcDe** [Woundorf/foxreplace#188]
I'm a bit stalled in some of my regular work because your otherwise great Add-On stopped working. Do you have any idea when the 17.3 will be approved? Or how could I install it from Git without needing "clearance" from Firefox?

**Comment by Woundorf** [comment]
It's currently in queue position 62 of 96, but it says that addons are not reviewed strictly in order. You can install the unreviewed version in Firefox Developer Edition. Sorry for the inconvenience.

**Comment by MarkMcDe** [comment]
Thanks! Will try to explore the Developer Edition, but knowing that the update is in the queue is helpful, too.

**Comment by MarkMcDe** [comment]
Turns out I do have the Developer Tools, but turning off the signature requirements does not allow it to upload either. Well, my older MacMini, which Mozilla no longer updates, still runs FoxReplace, so there's that handy.

**Comment by Woundorf** [comment]
Developers Tools are included in every Firefox. Firefox Developer Edition is another version of Firefox that you can get from here: https://www.mozilla.org/firefox/developer/

**Comment by MarkMcDe** [comment]
Hey I got the Developer Edition and found the new release works, just slowly. But now, hooray, the 17.3 release has been approved for regular Firefox, and everything works as it did before, maybe even faster! Now I just need to work out a problem with making it NOT select a string if it's followed by the lt bracket in lookahead that shows it's got an HTML tags wrapped around it. This looks mor like a StackExchange question.

Again, thanks much for this fine Add-On.
