### ISSUE TITLE
i want to call foxreplace using javascript  with foxgesture, how?

### ISSUE THREAD

**Issue by raphalelol** [Woundorf/foxreplace#195]
when you right click a page an item in context menu appears "replace with substition list (foxreplace)"

and it also gives me the option to use shift+f9

but i want to call that item using javascript so i can use gestures to excute it

how?

**Comment by Woundorf** [comment]
Well, I don't know about foxgesture, but if you can execute privileged code you should do ```foxreplace.listReplace();```. If this works and you want to do other actions you can take a look at the ```<command>``` items here: https://github.com/Woundorf/foxreplace/blob/master/content/foxreplace.xul
