### ISSUE TITLE
SyntaxError: JSON parse: expected ',' or '}' after property value in object at line 

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#196]
fr 0.17.1.1 signed.1 let fixed was working on my ff 44 on w10,
but today I made some changes in .json file, and when imported to ff-fr, it gave this error

`[IMG]http://i64.tinypic.com/15xq0b6.jpg[/IMG]`
`http://i64.tinypic.com/15xq0b6.jpg`

Error processing ISON from file E:\lang\fr\med1_en_hi.json. SyntaxError: JSON parse: expected ',' or '}' after property value in object at line 5471 column 51 or JSON data

All this cryptic languages, terminology, references are not becoming clear to me at all,
only if you could have displayed the line or a few lines where you are facing problem in accepting the json file input.

I created the json file throuch an excel file, in which formulae were there in excel as earlier, I have not made any changes in formulae, just added a few entries and pasted the final content from excel to json file in notepad++

when I open json file in notepad++ and go to line 1571, the following are lines 1570-1573 which seem ok to me
{"input": "हालत", "inputType": "text", "output": "दशा", "caseSensitive": false},
{"input": "' '", "inputType": "text", "output": """, "caseSensitive": false},
{"input": " × ", "inputType": "text", "output": " × ", "caseSensitive": false},

correspoding lines in excel file are like this
2	हालत	4	दशा		f	{"input": "हालत", "inputType": "text", "output": "दशा", "caseSensitive": false},
2	' '	3	"		f	{"input": "' '", "inputType": "text", "output": """, "caseSensitive": false},
2	 × 	3	 × 		f	{"input": " × ", "inputType": "text", "output": " × ", "caseSensitive": false},

other things are my sorting code, etc. 
only the last column with {"input": " onward is pasted to json file.

I am at a loss how to detect and solve the error. all work heldup.

please advise.

Thanks.
 -- 
Rawat

**Comment by Woundorf** [comment]
In the second line you show you have ```"output": """```. If you want to have a double quote character ```"``` in a JSON string you have to escape it with a backslash like this ```\"```. Thus you should have ```"output": "\""```.
