### ISSUE TITLE
Suggestion: Whitelist some websites please (or the opposite)

### ISSUE THREAD

**Issue by falzard** [Woundorf/foxreplace#198]
I use this extension to change some words and it's very funny sometimes. But sometimes it's annoying as hell because you don't want to change some words. For example you copy paste a text and many words are modified.

So it would help a lot if we could whitelist some websites. Or allow the filter only on some websites.

*I have another small suggestion, when you hover the mouse on a replaced word, it could change color or do something to show that it has been replaced.*

**Comment by Woundorf** [comment]
This is already present in the URLs tab: add example.com to whitelist it or a -example.com to blacklist it.

**Comment by falzard** [comment]
Sorry, I looked at everything but this part. I thought it was to replace URLs or something like that but now I see the button in the left corner.
Thanks and sorry.
