### ISSUE TITLE
Allow main Options window to be resized.

### ISSUE THREAD

**Issue by bulrush15** [Woundorf/foxreplace#199]
FoxReplace 0.17.3 on Firefox 49.0.2 on Windows 7.

The main options window is too skinny and I can't see enough information there with all the columns. Can you make it so we can resize it? And make the default size twice as wide? 

Thanks.
![foxreplace-mainopt](https://cloud.githubusercontent.com/assets/7031486/21350369/f5f8f20e-c684-11e6-9d68-bfea015a93dd.jpg)

**Comment by Woundorf** [comment]
It's already resizable if you open it from the toolbutton or from the menu (Tools -> FoxReplace -> Options). It's only not resizable if you open it from the addons tab, and I cannot change it (it's Firefox implementation).
