### ISSUE TITLE
How to exchange replacers with other users?

### ISSUE THREAD

**Issue by bulrush15** [Woundorf/foxreplace#201]
Can you make it so we can output a replacer to a text file and another user could import that replace, and FoxReplace would append that replace to his FoxReplace items? That would be very handy.

**Comment by SaltatorMortis** [comment]
do you mean the export feature?
it creates a json file that can be imported...
and if you want to keep other files permanent uptodate you can even import via URL on a fixed intervall

**Comment by Woundorf** [comment]
@bulrush15 What @SaltatorMortis is right, you can export a JSON file, send it to someone and that user can import it, all with the import and export buttons in the FoxReplace options window.
