### ISSUE TITLE
Firefox 52 release e10s to all, this extension disable it. Is this mandatory?

### ISSUE THREAD

**Issue by bullet92** [Woundorf/foxreplace#203]
From Firefox 52 changelog: "E10S for all users except those with extensions marked mpc=false"
Is that config mandatory for this plugin  to work? It would be nice an update that allow MPC to be true

**Comment by Woundorf** [comment]
The latest released version is not marked either way, but I have a branch where it's partially converted to WebExtension and is multiprocess compatible. I would like to have the transition in a more advanced state but if e10s is going to be enabled for everyone soon I'll have to release it soon.

**Comment by MarkMcDe** [comment]
Thanks for the notice. I'm seeing WordService and my own workflows stop working on Firefox. FR is still chugging along, thankfully, but for how long. It seems that if you can get this translated to a WebExtension, it would work with almost any browser, right?

**Comment by gerdneuman** [comment]
@Woundorf I use Developer Edition, i.e. FF 54 atm. Unfortunately, I had to remove Foxreplace to enable e10s. Since Foxreplace does not mark itself as e10s compatible. Hmm, a e10s release would be welcome. I think Foxreplace does even work under e10s it is just the info missing from its config file (afaicr)

**Comment by Woundorf** [comment]
@gerdneuman I released v1.0.0 which is multiprocess compatible 3 months ago, but it's taking forever to get reviewed by addons.mozilla.org.

**Comment by MarkMcDe** [comment]
Hey, the latest FF revision just came out. Getting FR to work was not a problem, but I was worried when my other Services stopped working. Now everything is fine.
