### ISSUE TITLE
Error when trying to import from URL

### ISSUE THREAD

**Issue by bulrush15** [Woundorf/foxreplace#204]
Foxreplace 0.17.3 with Firefox 51.0.1 on Windows 7 Pro. 

I have some JSON files for FoxReplace on Pastebin.com. But each time I try to import the Pastebin URL into FoxReplace I get an error. Test link to Pastebin and error in image below.

![foxreplerror](https://cloud.githubusercontent.com/assets/7031486/23857366/6f2ad892-07d3-11e7-9757-a6c2a1000b32.jpg)

Error is: "Error processing JSON from http://pastebin.com/xnTXWSeT: SyntaxError: JSON.Parase: Unexpected character at line 1 column 1 of the JSON data."

I'm not sure what is going on. Could it be FR doesn't support the CRLF combination that Pastebin uses?
Could there be a hidden control character as the first character?

**Comment by Woundorf** [comment]
This is because you are using a link that serves an HTML page. You have to use the raw link: http://pastebin.com/raw/xnTXWSeT
