### ISSUE TITLE
Allow FoxReplace to target specific elements?

### ISSUE THREAD

**Issue by Lemons224** [Woundorf/foxreplace#205]
Sometimes I think it would be nice for FoxReplace to be able to target specific page elements, like a specific text area, instead of always changing an entire page. Basically, I want certain things to change on a page and other things to be left alone. Thanks for reading.

**Comment by Woundorf** [comment]
Yes, I get what you mean. I've had this in mind since a long time, and will do it after finishing the port to WebExtensions.

For the moment I'll merge this with #56 which is basically the same.
