### ISSUE TITLE
Apply some substitutions automatically but others manually

### ISSUE THREAD

**Issue by SaltatorMortis** [Woundorf/foxreplace#206]
you can currendly only run scripts manally or automated on pageload.
but if you want a script optional it is only opssible to run every wanted regex over the 'replace Bar'.
can we get a option i.E. pinning a substitution list to the 'FoxReplace button' to call a group manually?
or shortcut it to a costum macro/press of the FoxReplace button

in addition to that it would be cool to get the option to create a (named) Template feature for the 'replace Bar'

i hope its i can define my suggestion understandable...

**Comment by Woundorf** [comment]
In the first part I understand that you want that some scripts are applied automatically but others manually. Is it that?

On the second part about the template, I don't understand what you want.

**Comment by SaltatorMortis** [comment]
jup that is right...
to put the second part simple i want to save often used regex
a simple on regex option of the first that is simply adjustable
but if the first is good implemented its basicly not needet...

**Comment by Woundorf** [comment]
Ok, then I'll focus on the first part when I have everything working with WebExtensions.

**Comment by Woundorf** [comment]
Implemented in cb84d2b, abed0e1 and 565b977.
