### ISSUE TITLE
What is the most efficient way of maintaining the case with regex?

### ISSUE THREAD

**Issue by seize21** [Woundorf/foxreplace#207]
Say the text is ‘say hello. Hello. hello,‘, how can it be changed to ‘say hi. Hi. hi.’ using 1 line of code?

**Comment by Woundorf** [comment]
There is no simple way to do it, you have to create substitutions for each case.

**Comment by seize21** [comment]
Are there if statements? This could somewhat help.

**Comment by Woundorf** [comment]
No, there aren't.

**Comment by camypaj** [comment]
Hi @Woundorf 
thank you for this amazing plugin! I know this "issue" is old, but I would like to reduce the click-bait-iness of certain websites, so I would ideally like to replace all caps with small letters. If I understand this right, that's not possible with FoxReplace?
Cheers

**Comment by Woundorf** [comment]
@camypaj What you are asking is different from the main question in this issue, that was how to keep case after substitution.

If you want to change everything to lowercase then it's possible and easy (just create a substitution for each letter from upper to lower (A->a, B->b, etc.). But if you want to keep some letters in uppercase (e.g. the first) then it's not currently possible.

**Comment by camypaj** [comment]
Hi @Woundorf that was a very quick response, thanks.
I've found another addon which might resolve this particular issue, but I'll still continue to use FoxReplace for another use-case. Thanks again for making this, it made my day, and probably the whole week :)
Cheers
