### ISSUE TITLE
Replacing only first occurrence

### ISSUE THREAD

**Issue by avoidik** [Woundorf/foxreplace#210]
HTML page with multiple images pointing to wrong URL. Simple rule to change one url to another processed only first occurrence and stopped. Replace in URLs option is set.

Trying to replace:
```
<img class="icon" src="http://10.0.0.2:8082/images/icon.png">
```

With this:
```
<img class="icon" src="https://fqdn.com/images/icon.png">
```

**Comment by Woundorf** [comment]
Is the whole page loaded at the beginning or is it loaded dynamically? What versions of FoxReplace and Firefox are you using?

**Comment by avoidik** [comment]
Lines are following one by one with not so much space between it. I try this not only with automatically option, but also manually after page has been loaded.

Firefox is 53.0.3 x64
FoxReplace is 0.17.3

**Comment by avoidik** [comment]
Replace option is simple text to find `http://10.0.0.2:8082/images/` with `https://fqdn.com/images/`

**Comment by Woundorf** [comment]
It's very strange then. I suppose there may be some error that stops the execution of the replacing script. I need to reproduce the error to know what is happening.

I suppose this is some private page, but maybe you can attach here the html file with confidential information removed, and if you can reproduce the problem with it then I should also be able to reproduce it.

**Comment by avoidik** [comment]
@Woundorf When I checked html template I found the problem and this is not related to FoxReplace. My apologies.

**Comment by Woundorf** [comment]
Ok, thank you for telling me.
