### ISSUE TITLE
Which other mozilla based browser foxreplace works?

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#218]
I had been using fr in ff

Today I wanted to use fr in K-maleon, palemoon and seamonkey.

 K-maleon seems not to have concept of add-ons, and has some macros.

But palemoon and seamonkey say fr can't be installed because it is not compatible.
through browser's add on search it is taking at the very same ff's fr page, and there is a message this add on (fr) is not compatible with your version of ff (I went using palemoon and seamonkey)

total confusion.

Which other mozilla based or any other browsers foxreplace works?

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment]
No other browsers are supported.

**Comment by vsrawat** [comment]
In my pale moon, an older version has got installed and is working.

I don't know which site it got automatically downloaded from.

They are using your work, without even informing you?

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment]
I suppose it works because Pale Moon was forked from Firefox, and I also suppose that it downloaded it from addons.mozilla.org. When I say that no other browsers are supported I mean that I haven't put any effort in making FoxReplace compatible with anything other than Firefox, but that doesn't necessarily mean that it can't work (although I don't think it can't work in anything that isn't forked from Firefox because the UI part depends on it).

**Comment by vsrawat** [comment]
This reply is only to confirm that fr is working perfectly well in palemoon.

Just that they have change the substitution keyboard shortcut from 
Shift-F9 to Shift-F8, that might cause some initial confusion that 
pressing Shift-F9 doesn't do anything so it is not working.

But press Shift-F8 instead, and it works.

the version there is 0.16.1.1-signed, so we might be loosing any 
improvement done in newer releases of fr, but I didn't notice anything 
so far.

So, as I myself had earlier wondered and several other users might wish 
to switch away from firefox but not able to do so just because fr didn't 
run in others, I confirm that fr works 100% well in palemoon.

Thanks.
-- 
Rawat

**Comment by vsrawat** [comment]
I think firefox is on the path of demise, like good old netescape.

ff has clubbed so many things in their new releases which are mostly 
useless and have bloated the code which makes browser use slow and cryptic.

And their memory management is an utter failure that browser starts with 
300 MB RAM usage and booms to 1GB+ on just a few tabs open, and doesn't 
clear that ram even after those tabs are closed. Then we have a single 
blank tab open, which is still using 1GB+ RAM.

Then, entire system becomes sluggish and browser stops responding, 
scripts give "continue/ stop" message after every 20 minutes as the 
browser itself is not responding, so scripts which would have finished 
execution in seconds, are taking 40 seconds, thus the message.

they have also removed several old features that I was using, and keep 
on addiing new things that I am not using.

I mean firefox has got damaged beyond repair.

And now I observe some recent add ons/ extentions working like "this 
extention wants access to your all data", - like gplus or fb apps are 
sking. No way I am going to allow that.

So I am dumping ff and have switched to palemoon, and I use chrome, 
yandex and ie extensively.

We can't even keep running old versions like ff30 or ff40, because they 
have changed sync so that new sync will not work in older releases, so 
we are forced to upgrade to newer versions.

I have to keep ff only because foxreplace runs on it.
-

The point is - most of ff users must be feeling the same problem and 
must be switching to other browsers and ff is dying.

And if fr works ff-only, so when ff dies, fr also is gone.

it is time you select at least one-two more browser and modify your 
extension so that fr works on those browsers also.

It will be sad if such a beautiful work of yours will not be usable by 
millions of users on account of its only browser dying, and it not 
working on other browsers.

palemoon could be one such browser because fr is already working in 
that, so it will require minimum additional work from you if you choose 
that for fr.

There are some problems in palemoon-fr also, that I am writing in that 
thread.

it is not just my individual problem. You must be having some thumb rule 
that when 10,000 users face the same problem, then one person writes 
about that on net.

Thanks.
-- 
Rawat

**Comment by vsrawat** [comment]
against as I previously reported, fr is not working properly in palemoon 
now.

the version there is 0.16.1.1-signed, it worked perfectly flawlessly for 
a few days.

Then problem appeared that my one 1.5 MB substitution table is not 
getting added to fr list. (it was previously working.)

Every step goes well, I "import", I click "append", it becomes visible 
in the list, I click ok and close the window and reopen fr properties to 
find that the table has disappeared.

It has happened 15 times in various ways. I have loaded that table 
alone, and loaded that with other 6 tables. Other 6 tables are getting 
loaded, appearing and working, just this 1.5 MB table is going missing 
after every load.

I have closed and restated palemoon, I have uninstalled and reinstalled 
fr extension. I have created another empty new profile and installed 
only fr, but nothing worked. This 1.5 MB table is never working.

The only thing I have changed in between is - I was previously using 
palemoon profile at w8 AppData, now I have copied the profile to my one 
E: folder so that my palemoon data don't disappear on next c: format or 
windows reinstall.
I don't know if that change caused this behavior.

of course, you don't support fr on palmoon, so please don't feel under 
pressure to do anything.

just that this info might be useful to some user.

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment]
I also think that Firefox is on a bad path in the last years, since they decided to start removing features that Chrome doesn't have and copying Chrome UI until it becomes Chrome with Gecko. But for this same reason I don't plan to switch to Chrome or IE (or Edge): I don't like their UI and I don't want to give Google and MS even more information.

In theory, after porting it to WebExtensions it should be easier to adapt it to some other browsers (Chrome, Opera, Edge). Maybe I will do it or maybe not, I haven't decided. But since FoxReplace is free and open source anyone can make a fork and do the required changes to port it to another browser, and even do a pull request to merge them here. Thus, if there is enough demand someone will eventually do it, either me or someone else.

As for your problem in Pale Moon, the problem is described in #145 and was fixed in v0.17.0. To summarize, there is a limit in the size of a preference in Firefox and so in Pale Moon. The list was saved in a preference up until 0.16.* (you can see it in about:config, search for foxreplace), and since 0.17.0 it is saved in a file to avoid this problem.

**Comment by vsrawat** [comment]
I checked both in ff and in pm

The only new key appearing in pm is
extensions.foxreplace.substitutionListJSON
with string value {"version":"0.15","groups":[]}

checked on #145, but the solution mentioned is "Fixed in r245."

I had tried updating fr to newer versions in pm, but nothing newer than 
0.16.1.1-signed is getting updated, giving message, "not compatible with 
palemoon".

So I am stuck. I have to continue with ff as long as fr works in that.
or maybe pm releases a new version removing that restriction.

:-(

Thanks.
-- 
Rawat

**Comment by rufus64** [comment]
For anyone reading, 0.17.0 appears to work on Pale Moon 33.0.0, got no compatibility errors.

**Comment by vsrawat** [comment]
Yes, I ran some substitutions, and for my two sets of lists,
foxReplace 0.17.1.1-signed.1-let-fixed seem to be working.

My substitution list json data files are of "version": "2.1".

The bottleneck could be the limitation of 1MB or whatever size of the 
substitution list json data files that was there in earlier versions of 
fr and was removed in some later version, I don't know which version.

if 0.17.1.1 is after that critical update and could support larger json 
files, this is all good, otherwise not much relief.

Someone could please crosscheck or tell which version onward larger json 
files were supported?

I cannot ever thank you enough for making this magical add-on. It has 
been a great help to me across the years, even decades, and still going 
strong.

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment]
> Someone could please crosscheck or tell which version onward larger json files were supported?

Let me quote myself:

> As for your problem in Pale Moon, the problem is described in https://github.com/Woundorf/foxreplace/issues/145 and was fixed in v0.17.0. To summarize, there is a limit in the size of a preference in Firefox and so in Pale Moon. The list was saved in a preference up until 0.16.* (you can see it in about:config, search for foxreplace), and since 0.17.0 it is saved in a file to avoid this problem.
