### ISSUE TITLE
Stopped working after update 9Sep17

### ISSUE THREAD

**Issue by FalconDot** [Woundorf/foxreplace#221]
Disappeared from menu and contextual menu.
Shift-F9 opens storage in debugger.
Thank you!!

**Comment by Woundorf** [comment]
Have you tried restarting Firefox to see if the menu items come back?

Shift+F9 has been taken by Firefox, so in the latest version I changed it to Ctrl+F9.

**Comment by FalconDot** [comment]
Thank you Marc,

I didn't check Ctrl+F9.
Restarted FireFox with all Addons off but FoxReplace going.
At a glance, not appeared in menu and contextual menu too.
Not sure where to change settings...

Cheers
Dmitry

**Comment by Woundorf** [comment]
Restart Firefox again, press Ctrl+Shift+J to open the browser console and tell me if there is any error there. Copy and paste it here or make a screenshot if there is something.

**Comment by lakefield2** [comment]
I have the same problem. No possibility to change the settings of FoxReplace.

**Comment by Omwrecker** [comment]
I had that problem too, just uninstall the addon. Restart firefox and redownload the addon.

**Comment by lakefield2** [comment]
Thanks! Worked for me (settings remained unchanged).

**Comment by FalconDot** [comment]
Thank you @Omwrecker. So easy...
Added to LikeInMind for future references:
http://confocal-manawatu.pbworks.com/w/page/120242403/FoxReplace%20Stopped%20Working
LiM is our memory.
