### ISSUE TITLE
this russian word dont get replaced

### ISSUE THREAD

**Issue by rezad1393** [Woundorf/foxreplace#224]
this Russian word doesn't get replaced with its translation (united kingdom)

"Великобритания"

foxreplace ver:1.13
firefox 55.0.3

**Comment by Woundorf** [comment]
Have you correctly defined the substitution?

Version 1.13 doesn't exist, I suppose you mean 1.1.3.

**Comment by rezad1393** [comment]
yes and yes.
all the other words work except this one.
big words like Документальные and so on work too but I dont know why this one doesnt.
the weird part is that it work on the page 
[https://rutracker.org/forum/tracker.php?nm=%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B1%D1%80%D0%B8%D1%82%D0%B0%D0%BD%D0%B8%D1%8F](url) but it doesn't work on this page [ https://rutracker.org/forum/viewtopic.php?t=205511](url)
all the other word woks allways.

**Comment by Woundorf** [comment]
This word in the thread title has an HTML element in the middle: `Великобритан<wbr>ия`. That's why it's not found by FoxReplace.

**Comment by rezad1393** [comment]
I cant translate that unless I use the html replace option right?

**Comment by Woundorf** [comment]
Right. HTML input & output and put `Великобритан<wbr>ия` as the input.
