### ISSUE TITLE
1.1.3 marked as Legacy in Firefox 57.0b4

### ISSUE THREAD

**Issue by Merseybuoy** [Woundorf/foxreplace#225]
Had version 1.1.3 working in Firefox 56.0, but doesn't work in 57.0beta.

**Comment by Woundorf** [comment]
I have to release a WebExtension version for this. I will publish it as soon as possible.

**Comment by Merseybuoy** [comment]
Thanks Marc.  For some reason I thought 1.1.3 was a webext version.

**Comment by Woundorf** [comment]
1.1.3 is an hybrid version, i.e. partially classic extension partially WebExtension.

**Comment by Merseybuoy** [comment]
I don't suppose there is any chance of having 1.1.3 working in Firefox 52.0ESR? Being able to open the interface as a tab and then leave it open is much more convenient than version 1.0 window.

**Comment by Merseybuoy** [comment]
Thanks for the info.
