### ISSUE TITLE
[Feedback] Hei Marc, can you bring back the F2...

### ISSUE THREAD

**Issue by standoski** [Woundorf/foxreplace#227]
Hello!

Marc in the past F2 was the king key for FoxReplace :)

Now in FF57, the F2 is free. Can you set the F2 to do again the "Replace with the substitution list" ?

Thanks!

PS: Keybinder is not compatible with FF57.

**Comment by Woundorf** [comment]
Hi, you are right, F2 is not used in Firefox, but it's used in Google Docs for example and that was an issue for me and maybe for other people. So, for the moment I prefer to leave it as it is. But I can try to make the shortcuts configurable in the future.
