### ISSUE TITLE
can you add an option to disable context menu added by foxreplace?

### ISSUE THREAD

**Issue by rezad1393** [Woundorf/foxreplace#229]
can you add an option to disable context menu added by foxreplace?
Firefox no longer gives access to xul and other ways to disable context menu.

**Comment by Woundorf** [comment]
Ok, I'll make it optional.

**Comment by rezad1393** [comment]
thanks.
too many addons just add context menus with no regard to user preferences.

**Comment by Woundorf** [comment]
Done in 5acee79.

**Comment by rezad1393** [comment]
thanks
