### ISSUE TITLE
using RE: if you want to replace a space with anything else...

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Woundorf/foxreplace#23]
```
replacing a space with anything else using the RE replaces everything on
the web page, whether from code or from editable text areas... is there a
way to configure this add-on to run on text boxes only ?

```

Original issue reported on code.google.com by `khaledha...@gmail.com` on 21 Nov 2009 at 11:20

Attachments:
* [Picture 11.png](https://storage.googleapis.com/google-code-attachments/foxreplace/issue-23/comment-0/Picture 11.png)

**Comment by Woundorf** [comment]
This can be considered a duplicate of #56.
