### ISSUE TITLE
Replace with substitution list not working, forced to use automatic replace

### ISSUE THREAD

**Issue by CoolsyNitro** [Woundorf/foxreplace#230]
I've gotten the latest version of FoxReplace and I can't use the "Replace with substitution list" to  substitute words I need changing. I hit Ctrl + Fn + F9 (cause I'm on a Mac) and nothing happens. I select the option manually from the Tools tab and nothing happens. If I change the settings to replace words with the substitution list every X seconds though, it works. Is it a problem on my end or the actual addon? It's very tedious to keep changing the settings just to get it to work

**Comment by Woundorf** [comment]
Hi, you have encountered two different problems in fact.

The first one is that the shortcut is always written as Ctrl+F9 in all platforms but it's actually Cmd+F9 (or Cmd+Fn+F9) on Mac. I didn't think of this.

The second one is that the option in the Tools menu doesn't work on any platform, but the context menu and tool button items work correctly.

I'm going to fix both problems for the next release. Sorry for the inconvenience and thanks for the report.

**Comment by Woundorf** [comment]
Fixed in e5ee418 and 4829a6b.
