### ISSUE TITLE
Cannot Right-Click And Replace Words From Shell Anymore

### ISSUE THREAD

**Issue by Anigai** [Woundorf/foxreplace#232]
Windows 7
Firefox v57.0.1
FoxReplace v2.1.0

With the change wherein now "Apply manual substitutions" and "Apply automatic substitutions on page load" appears solely in the Tools menu I can no longer right click on any page and apply the substitution list.

I have to exit fullscreen, open the tools menu, use the "Apply manual substitutions" then re-enable fullscreen and this needs to be done on every new page load unless you want to use the auto sub list replace option.

For useability sake for regular run of the mill people this is a step backwards. 
As is the new tabbed interface over the previous windowed inferface.

**Comment by Woundorf** [comment]
If you mean the context menu you can enable it from the options page: under "Other options", "Enable context menu", click Save. You can also use Ctrl+F9.

The tabbed interface is imposed by the current versions of Firefox.
