### ISSUE TITLE
URL of Router is Ignored in Auto Substitute

### ISSUE THREAD

**Issue by sqgl2** [Woundorf/foxreplace#234]
My router is at http://192.168.1.1/ but the substitutions only work in manual mode. Firefox actually shows the URL as 192.168.1.1 without the http FWIW but I did try simply putting 192 in the URL field and that also did not work for auto sub.

However I have a [sticky note](https://addons.mozilla.org/en-GB/firefox/addon/sticky-notes/) associated with that router's web page and it _does_ get subtituted.

**Comment by Woundorf** [comment]
Hi, I have tried a simple substitution with my router which is at the same IP and it works both in auto and manual. Have you verified that all settings are correct? (substitution in auto or auto&manual, apply automatic substutions checked, click the save button, etc.)

**Comment by sqgl2** [comment]
The sticky note would not have the substitutions performed on it if I had not done all the other things correctly. Now I think about it, perhaps the issue is because there are modem pages auto-refreshing (does not have to be the one I am viewing)? Those kind of javascripts do not play nicely with FoxReplace.

Router is TP-Link Archer D7 AC1750.

Even a perpetual linux tail command does not work with FoxReplace.

**Comment by Woundorf** [comment]
> The sticky note would not have the substitutions performed on it if I had not done all the other things correctly.

Do you mean that automatic substitutions are failing on the notes, or on the regular page as served by the router? In the first case it could be that the notes are inserted after FoxReplace has done its things. If it fails also on the regular pages then it could be because of the auto-refreshes, as you say.

**Comment by sqgl2** [comment]
> Do you mean that automatic substitutions are failing on the notes

No, I mean that they work on the notes.

> it could be because of the auto-refreshes, as you say

OK, I can live with that.

**Comment by Woundorf** [comment]
Ok, then I will close this.
