### ISSUE TITLE
"unterminated parenthetical" warning no longer generated

### ISSUE THREAD

**Issue by sqgl2** [Woundorf/foxreplace#236]
The old version v1.0.0 gives a sensible warning message re unpaired parentheses when I try to import a badly formatted regex which was saved with_out_ complaint in v2.1.0

**Comment by sqgl2** [comment]
Actually both the old and the latest version give a warning on import. The question then is: why not give the warning upon the save?

**Comment by Woundorf** [comment]
I'll have to take a look on it to know.

**Comment by Woundorf** [comment]
When entering a regexp with an unclosed parenthesis through the editor and then saving, the next time the options page is loaded this can cause the issue explained in #223, where the list box just shows "Loading" and there is no way to edit the list.
