### ISSUE TITLE
Automatic save of options is good, but...

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#242]
Automatic save of options is good, but
what would we do if we had done some mistake in updating the files, and we have to abort?

I mean, when are the options saved automatically,
1. as soon as we upload a json file? or
2. when we close the options tab?

please clarify.

I still feel that a "save" "abort" buttons or both was clear enough, just that "save" at so much down below is not good. it would have been good if  save/ abort buttons were right next to "clear" button.

**Comment by Woundorf** [comment]
Options are saved after any change (with the exception of editing a group, then the changes are saved when you click ok or apply). In your example this means that they are saved when you upload the file.

If you make a mistake, then you better have a good copy. Maybe I could implement some kind of automatic backup so you could revert to a copy from a few days before in case of a problem.
