### ISSUE TITLE
In 'Type' column the drop down box moves down the page.

### ISSUE THREAD

**Issue by Merseybuoy** [Woundorf/foxreplace#248]
For several weeks I've noticed that I couldn't bring up the drop down box to change between Text and Whole Words and Regular Expressions. 
Purely by chance I've found that it is moving down the page with every line selected until it disappears off the bottom of the screen. So, with zoom set to 100%, I can see the drop down box for approx. 25 lines, then after that it has moved off the bottom of the screen.

**Comment by Woundorf** [comment]
I can't reproduce this. I have tried reducing the window size but then the dropdown opens upwards. Can you send a screenshot of what you see?

**Comment by Merseybuoy** [comment]
Hi Marc. I do wonder if their is something about my system that causes these problems.

Pic 1. Line a. No problem.
![screenshot001](https://user-images.githubusercontent.com/29621632/42175863-e7913408-7e1e-11e8-9a38-8bdcec0b0658.jpg)
Pic 2. Line w. Only half the box is visible.
![screenshot002](https://user-images.githubusercontent.com/29621632/42175871-ed0499de-7e1e-11e8-9e26-f511e39058f8.jpg)
Pic 3. Line Z. Only the top of the box can be seen at the bottom of the screen.
![screenshot003](https://user-images.githubusercontent.com/29621632/42175878-f26954f0-7e1e-11e8-8270-ea0d36526116.jpg)
Pic 4. Line 5. 50% zoom shows box way down off the bottom.
![screenshot004](https://user-images.githubusercontent.com/29621632/42175883-f6cfdbfe-7e1e-11e8-9410-f77dfb30fe2c.jpg)

**Comment by Woundorf** [comment]
I can only manage to get something similar to this if I double click to edit a row and then scroll up the whole way up. Then the dropdown is approximately in the same position as yours, but of course I see the top of the list starting from 'a'. But this may be a clue to the problem.

One last question, though: what version of Firefox are you using? If you have found it just now maybe it happens only in newer versions (I have tried now in an old version).

**Comment by Woundorf** [comment]
Ok, now I have tried on a newer version and I can reproduce the problem. It works well in Firefox 57 but badly in 61.

**Comment by Merseybuoy** [comment]
Using Firefox 62.0 beta4. 64bit. I always use the latest beta.
