### ISSUE TITLE
unable add new rule in settings due to popup

### ISSUE THREAD

**Issue by ssbarnea** [Woundorf/foxreplace#250]
I keep getting the "You must add at least one substitution and correct all errors" popup which prevent me from adding a new rule. There is no other indication about what could be wrong with the rule
- it as a name
- it has an url
- it has a substitution added

**Comment by SaltatorMortis** [comment]
have you pressed ENTER?
its not saved if you don't manually confirmed the Regex
if you don't have a Row with (Type input...) below your List it is not confirmed(happens if you switch to the URL tab prior to pressing Enter)

**Comment by Woundorf** [comment]
Probably it's what @SaltatorMortis said, the substitution (the only required thing) was not finished to enter. I know that the UI requires a lot more work.

**Comment by ssbarnea** [comment]
@Woundorf Yep, I figured it out after few minutes. Still, please keep this bug open as a reminder that the UI needs a lot of work. At this moment feels like web of 90s.

And btw, thanks for doing a good work on this. I am using it to highlight build logs, to make them readable.

**Comment by JanisE** [comment]
@SaltatorMortis , thank you, pressing [Enter] worked. I was almost discarded this extension as non-working...

**Comment by ssbarnea** [comment]
I had a big lauch at @JanisE comment as a couple of months ago I was in the same place, ready to ditch the newly installed extension because the UI was impossible to use. Meanwhile I got used to it, I still hate it (the UI). Now I prefer to edit the config outside and import it.

**Comment by gisforgirard** [comment]
literally would never figure this out without this discussion page, there's gotta be a more intuitive way or something

**Comment by Woundorf** [comment]
Thanks @gisforgirard, I hadn't seen this.

**Comment by gisforgirard** [comment]
No prob, I was in the same boat about to throw away the plug-in and find
another, except there isn't another worthwhile one, and this one works fine
but the setup dialog is just a little wonky 😂 but we can fix it, we have
the technology haha

I don't know enough about JS to actually fix this one, but I traced it down
best I could to help out someone who maybe can. I figure you just set that
in the initialization somewhere and it should be all good...

**Comment by hjk321** [comment]
A potential quickfix in the meantime while this is being worked on could be to add some text to the popup, "(Did you press enter?)" or something of the sort. This will send confused new users in the right direction until we can get stopEditingWhenGridLosesFocus implemented.
