### ISSUE TITLE
document similar tools that are able to replace text in browser based on regex

### ISSUE THREAD

**Issue by ssbarnea** [Woundorf/foxreplace#251]
I am really looking for a browser extension that would allow me to annotate (highlight) plain text log files using multiple regex expressions and it would be really nice if foxreplace would document similar work. I am sure other extension developers will do the same in return.

Sadly FoxReplace does not seem usable to me for several reasons (don't take my feedback a negative, is still the closest solution I found in weeks):
- crashes latest Firefox on file upload dialog on Mojave (probably unrelated)
- not working well with Firefox Developer Edition (which apparently works with file upload)
- user interface is a nightmare, lucky I could use URL + json to avoid it. it is extreamly unintuitive and gives no feedback to the user, for example the need to press enter to save new rule is a well guarded secret :D

**Comment by Woundorf** [comment]
The only similar tool that I know of is Word Replacer II in Chrome, as commented by a user in #197, but I haven't tried it much.

As for the other problems:

> crashes latest Firefox on file upload dialog on Mojave (probably unrelated)
I can't try it.

> not working well with Firefox Developer Edition (which apparently works with file upload)
Could you explain the problems (preferably in a new issue)?

> user interface is a nightmare, lucky I could use URL + json to avoid it. it is extreamly unintuitive and gives no feedback to the user, for example the need to press enter to save new rule is a well guarded secret :D
I know it needs a lot of work.

**Comment by ssbarnea** [comment]
Closing it because: FoxReplace works with Firefox Develoeper Edition too and the upload crash with stable Firefox is related to Mojave, and not the extension.
