### ISSUE TITLE
Information: fr works in Basilisk/ Light browsers, stopped working in Palemoon v28

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#254]
This is not an issue, just information that might be useful for some users.

fr version 0.16.1.1 is working in palemoon browser up to version 27.9.2 (I tested on 64 bit)

Recently I updated to pm version 28.0.0 and found the fr is giving problem, it was partly working, some tables were working, some were not. I couldn't figure out the logic or method of that.

I updated to some versions of fr in add-on in that, but the same behavior continued.

I reinstalled palemoon 27.9.2, and found that fr versions higher than 0.16.1.1 are not supported.

so, I am back to fr version 0.16.1.1 and palemoon 27.9.2 which are working perfectly well.
--
Also, fr 1.0.0 is working well in basilisk browser v2018.06.01 64 bit

Also, fr 0.17.3 is working well in Firefox Light browser 47, I think that is 32 bit.

Developer says he doesn't support fr for any browser other than firefox, but if any of you need to use fr in other browser, the above might come handy.
--
Why do I need to run fr in so many browsers?
There are some 4-5 sets of 2-3-4 conversion tables that I have to repeatedly run on certain text, and I found it complicated to activate-deactivate those sets of tables in fr Options every time in ff.
So, I have put each set of tables in different browsers and I don't need to activate-deactivate, I just run that browser and do fr conversion there for that type of conversion.

May be, developer can provide a method of grouping tables so that those can be activated/deactivated in one go, instead of we manually ticking-unticking each table individually.

Thanks.

**Comment by vsrawat** [comment]
sorry for those bold paragraph. I typed normally and the site automatically made them bold. I don't intend to convey anything specific by that boldening.

**Comment by JanisE** [comment]
@vsrawat , just edit your post and remove the boldening then.

**Comment by marsjaninzmarsa** [comment]
> So, I have put each set of tables in different browsers and I don't need to activate-deactivate, I just run that browser and do fr conversion there for that type of conversion.
> 
> May be, developer can provide a method of grouping tables so that those can be activated/deactivated in one go, instead of we manually ticking-unticking each table individually.

`Win`+`R`, `firefox --ProfileManager`, enter, you're welcome.
