### ISSUE TITLE
regex $0 not expanded as the full match

### ISSUE THREAD

**Issue by ssbarnea** [Woundorf/foxreplace#256]
As far as I know regex standard behaviour is to use $1 for first block match, $2 for second and so on with the $0 marking the entire matching text.

Shile $1 works well, I observed that $0 is expanding to noting which is not expected.

Example:  `foo bar zoo` text with expression `foo (\w+)` should return: set $1 as `bar` and $0 as `foo bar`, but the second part is not happening.

**Comment by Woundorf** [comment]
This is [how JavaScript works](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter):

> $n: Where n is a positive integer less than 100, inserts the nth parenthesized submatch string, provided the first argument was a RegExp object. **Note that this is 1-indexed.**

So I can't change it.

**Comment by ssbarnea** [comment]
Thank for the doc link. Shortly the JS version that works is $&
