### ISSUE TITLE
Some Subtitutions Fails Since Update to v2.2.2

### ISSUE THREAD

**Issue by sqgl2** [Woundorf/foxreplace#261]
I have to remove some substitution groups to get FR working at all. Firstly I deleted everything up to (what seems to be) the offending group to get FR working. Thinking there was a bad command here (unlikely since I hadn't changed it in a year) I tried re-importing the entire definitions file but this time removing just the suspect group however that did not work. I really had to remove all the groups above it too.

Even then one substitutions definition fails to do anything anymore: 
Replace Plain Text:
`<FONT color="yellow">XXX</FONT>`
With:
`YYY`
HTML=input&output is set

The problem only started happening about 5 days ago, which is the date of the v2.2.2 update.

**Comment by sqgl2** [comment]
I haven't forgotten but it requires changing the password on a shoutcast admin page for you temporarily. Will eventually do it.

**Comment by sqgl2** [comment]
You can remove this zombie bug. I fixed it. Wasn't a problem with FR.

**Comment by Woundorf** [comment]
OK, thanks.

**Comment by sqgl2** [comment]
I see there has not been much activity.
I expected your plugin to gain in popularity but it seems not for some strange reason.
Have you put the project on hold?
Is the version updated automatically by Firefox?
How do I see what my version is?

**Comment by Woundorf** [comment]
I haven't devoted much time to it in the last few months, mainly due to lack of motivation. I will continue development when I regain motivation. In the meantime I respond to issues.

Unless you have changed something in Firefox, it is updated automatically. You can check the version at about:addons clicking on it. The latest version is 2.3.2.
