### ISSUE TITLE
How to replace texts with HTML entities

### ISSUE THREAD

**Issue by hanuiv1** [Woundorf/foxreplace#262]
I have text containing "&nbsp;" entities. I was trying to find a way, how to replace those, but no luck.
Can someone advise, how to: replace:
aaaaaaaa &nbsp; bbbbbbbbbbb with 
ccccccccc &nbsp; ddddddddddd ?
Thank you!

**Comment by Woundorf** [comment]
You have to write the nbsp character using one of [these methods](https://en.wikipedia.org/wiki/Non-breaking_space#Keyboard_entry_methods) or copy it from the character map. Put it in the appropriate place in the Replace field.
