### ISSUE TITLE
change shortcut key?

### ISSUE THREAD

**Issue by rezad1393** [Woundorf/foxreplace#266]
can an option be added to change or disable shortcut for showing  of foxreplace? from F9.
it interferes with a web financial app I use.

**Comment by Woundorf** [comment]
I will see how to make it configurable.

**Comment by rezad1393** [comment]
ty

**Comment by 07416** [comment]
The hotkey F9 interferes with _Firefox's reader mode_.

https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_miscellaneous

**Comment by 07416** [comment]
Changing the shortcut is now possible natively: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
