### ISSUE TITLE
SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 6 column 1 of the JSON data

### ISSUE THREAD

**Issue by praneethvallabha** [Woundorf/foxreplace#271]
I'm trying to run a code:
{
"$class": "org.clearing.SubmitTransferRequest",
"transferId": "1111",
"state": "PENDING",
"toBank": "222"
"details": {
"$class": "org.clearing.Transfer",
"currency": "EURO",
"amount": 150,
"fromAccount": "987654321",
"toAccount": "123456789"
}
}
can someone help!
![screenshot from 2019-03-06 23-52-28](https://user-images.githubusercontent.com/44611528/53919663-fdc88a00-406a-11e9-9716-77051d1cb4d4.png)

**Comment by Woundorf** [comment]
I don't see what this has to do with FoxReplace, but you are missing a comma after "toBank": "222".
