### ISSUE TITLE
FoxReplace change web content before it is visible...

### ISSUE THREAD

**Issue by DaZealous** [Woundorf/foxreplace#272]
The issue am having here is that, I want the FoxReplace to change the text before the content of the web page becomes visible...pls I need help

**Comment by Woundorf** [comment]
This is not possible with FoxReplace, and I don't even know if it's possible to implement with WebExtensions, so I will close this.

**Comment by DaZealous** [comment]
Alright thanks bro, but can I connect the extension to firebase??

**Comment by Woundorf** [comment]
Are you referring to Google Firebase? I suppose that you can use it there, I don't know if you mean another thing by "connect".

**Comment by DaZealous** [comment]
Yeah google firebase

**Comment by DaZealous** [comment]
What I want is that I should be able to store and retrieve the text I wanna change from firebase...

**Comment by Woundorf** [comment]
So you mean saving the substitution list in Firebase and that the extension retrieves it from there?

**Comment by DaZealous** [comment]
Yeah, exactly what I want sir...I don't know if you can be of help.

**Comment by Woundorf** [comment]
Well, you can edit the list from FoxReplace, export it to a file and upload that file to Firebase. Then get its URL and use it in "Import from URL" or "Update periodically from URL" in another FoxReplace installation.

**Comment by DaZealous** [comment]
Alright thanks bro, I have done that and it is working fine..but I also want to get the selection of the text being changed and save it to firebase. Thanks

**Comment by DaZealous** [comment]
Pls I need help on this sir...

**Comment by Woundorf** [comment]
If you mean getting a list of the changes between the original version and the replaced one, then this is not implemented.

**Comment by DaZealous** [comment]
I mean the original text that's displayed on the web page before its being
changed..Thanks.

**Comment by Woundorf** [comment]
Well, then you will have to save it yourself before applying the substitutions.

**Comment by DaZealous** [comment]
Yeah....but what happened was that I saved a bunch of text in a regex
pattern..so foxreplace searches and replace any text that matches the one
on the web page...so its not possible for me to know the particular text
that is being changed, because the web page generates the text randomly...
Anyways thanks...I really appreciate
