### ISSUE TITLE
URL matching

### ISSUE THREAD

**Issue by stonecrusher** [Woundorf/foxreplace#275]
Hi,
I'd like to know more about how the URL matching works.

Apparently wildcards `*` are added automatically at the start and end of the string.
Wildcards work (greedy) in the middle of a string.
Joker `$` for single characters doesn't work.
RegExp doesn't work (would be awesome to create rules like "apply everywhere except example.com")

Am I right with those? There is not explanation, no info box?!

**Comment by Woundorf** [comment]
Hi, the info box was lost in the transition to WebExtensions and I had forgot about it, but sure it should be added again.

Special characters in URLs are wildcards `*`, that matches 0 or more characters and they are implicit at the beginning and the end, and `|`, that can be used at the beginning and the end to avoid the implicit character. For example, `http://*.example.com/|` would match `http://www.example.com/` but not `http://www.example.com/whatever`. RegExps are not accepted here.

If want to apply everywhere except example.com you can add an hyphen at the beginning, e.g. `-example.com`. It will be shown in red to indicate that it is where it doesn't apply.

**Comment by stonecrusher** [comment]
Ah ok, thank you for the helpful information!
However it would be nice to reintroduce the lost infobox so everyone can profit.

**Comment by McBobb** [comment]
I tried adding the "|" character at the start of straight URL replacement statements to make sure that multiple specific URL obfuscations are not applied all at the same time, but it doesn't work. The edited expression doesn't even recognize the URL obfuscation I wanted to fix.

For example; I wanted FoxReplace to change "hs://" at the beginning of URLs with "https://", so I put "|hp://" in the Replace field, and "https://" in the With field, but it doesn't work. Do I need to add the wildcard to the end of the Replace statement?

**Comment by Woundorf** [comment]
That `|` character is to match the URLs where substitutions are applicable, but not to match anything in the Replace field. There you can use the usual plain text, whole words or regular expression. You could use a regular expression like `^hs://` (or `^hp://`, you have written both in your comment and I don't know which one do you intend) to get the same effect you want.
