### ISSUE TITLE
replace with regex?

### ISSUE THREAD

**Issue by alionar** [Woundorf/foxreplace#277]
can you  help me to replace based on existing url parameter on this link?

so when browser load page with this link text
`http://www.website_1.com/redirect.php?url=http://www.website_2.com/image/40850f1000979174`

i want foxreplace to change it to 
`http://www.website_2.com/image/40850f1000979174`

in foxreplace i just did this:
- Replace `http://www.website_1.com/redirect.php?url=([^&]+)`
- Type `ReGex`
- With `$1`
- Match Case: `Checked`

but nothing happen

thanks

**Comment by Woundorf** [comment]
You have to check the replace urls option in the options page.

**Comment by alionar** [comment]
already checked that option, but still nothin's replaced

**Comment by Woundorf** [comment]
I realise now that '?' is a special character. You have to escape it with a backslash, i.e. '\?'. I recommend to escape dots as well as they are also special characters.

**Comment by alionar** [comment]
i already change regex pattern with escape character
`http:\/\/www\.website_1\.com\/redirect\.php\?url=([^&]+)`

still not replace, and i don't know what to set right now.

**Comment by Woundorf** [comment]
But does it replace something now or still nothing? The regex is now correct as tested with https://regexr.com/

**Comment by alionar** [comment]
still do nothing, no link with that regex paettern was replaced

**Comment by Woundorf** [comment]
Are automatic substitutions enabled?

Is the page content loaded dynamically?

**Comment by alionar** [comment]
i already enable automatic substitutions and i guess page content don't loaded dynamically (i use this  regex to replace redirect link in forum post that use xenforo forum software)

**Comment by Woundorf** [comment]
When copying the regex from your comment I got a blank space just before the 'h' of http that made it fail. Check that you don't have any space at the beginning or the end of the regex.

I have tried it here http://b37df1a99ed069ec.demo-xenforo.com/212/index.php?threads/prova.1/ with your example link and it works if there aren't trailing spaces.

**Comment by alionar** [comment]
There's no space at beginning and the end of the regex pattern. maybe because of code markdown.
[img]https://i.imgur.com/9K8qM3d.png[/img]

I tried your forum link and it worked.
[img]https://i.imgur.com/yWzmpPb.png[/img]

I think in my forum, the admin (maybe) use some anti-replace method for redirect link so user can't replace their redirect link and they can put ads in redirect link page.

**Comment by Woundorf** [comment]
I can't imagine how they could avoid replacements, but at this moment I'm out of ideas.

**Comment by alionar** [comment]
ok then, thanks for your help :)
