### ISSUE TITLE
Automatic replacements ceased to work

### ISSUE THREAD

**Issue by imya-polzovatelya** [Woundorf/foxreplace#278]
Hi! Thanks for important addition of Firefox, I use it for working long ago.
After updating of May 25 automatic replacements ceased to work. It is impossible to configure — at any combination of parameters the message of "You must add at least one substitution and correct all errors". Please help, how to correct a problem? Thanks in advance.

**Comment by Woundorf** [comment]
This has not changed, it's the same issue as in #250. You have to press Enter to confirm the substitution. I will fix this, but I don't really have time now. Sorry for the inconvenience.
