### ISSUE TITLE
F9 is'nt working

### ISSUE THREAD

**Issue by SimonVilleneuvewp** [Woundorf/foxreplace#279]
Hi,

Since a day or 2, the F9 shortcut isn't working. It seems to have been taken by the new pocket app.

I don't know how to use FoxReplace anymore. Someone can help ?

**Comment by Woundorf** [comment]
The F9 shortcut has been changed to Shift+Ctrl+F9 because F9 is now used by Firefox itself. If you prefer another shortcut you can go to about:addons, click on the gear button and on "Manage Extension Shortcuts" and set your preferred shortcut.

**Comment by SimonVilleneuvewp** [comment]
Thank you very much for this fast and clear answer !
