### ISSUE TITLE
Performance - is it faster, if there is no match (using more distinct rules)

### ISSUE THREAD

**Issue by MeilEsdelhi** [Woundorf/foxreplace#280]
As I have a lot of replacement rules slowing the process I ask myself, which of the following is faster:

Condition: I have different rules for making words upper case.

A) I have a rule which finds a string to replace, although it does not change it (because it is **not** case sensitive and it has already been changed to upper case)
B) I set this rule to case sensitive **true**, so the rule is more complex, but no replacing is done.

(Example:
*Condition* world->World
*rule* worldcake->Worldcake
)

**Comment by Woundorf** [comment]
Is this a question or what? If it's a question, I don't know the answer, you will have to try it.
