### ISSUE TITLE
Can this be made to work with never ending reddit?

### ISSUE THREAD

**Issue by JamesG269** [Woundorf/foxreplace#283]
If you're not familiar, a popular extension called Reddit Enhancement Suit allows you to keep scrolling down and it will load the next page of reddit. On chrome, I used the extension 'word replacer II', and it could replace words as never ending reddit loaded new pages, so I figure this should be possible here.

**Comment by Woundorf** [comment]
You can try the "Apply automatic substitutions every few seconds" option.
