### ISSUE TITLE
how to use parenthesis to use it as selection command and not to take it literally

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#284]
I have input like 
10ml
23mg
in which units ml (milliliter) or mg (miligram) are put together with the numerals denoting quantity that creates problem in matching/ finding/ translating.

I want to insert a single space between numeral quantity 10, 23 and units mg, ml

I have made this foxreplace json file entry.
`{"input":   "([0-9])m(gl)", "inputType": "regexp",   "output": "$1 m$2", "caseSensitive": false}`

It is not working.

putting single \ before opening/ closing parenthesis ( and ) 
`{"input":   "\([0-9]\)m\(gl\)", "inputType": "regexp",   "output": "$1 m$2", "caseSensitive": false}`
or double \\ before opening/ closing parenthesis ( and ) 
`{"input":   "\\([0-9]\\)m\\(gl\\)", "inputType": "regexp",   "output": "$1 m$2", "caseSensitive": false}`
also doesn't work

Any help what I am missing.

how many times () are to be escaped by using slash to make it work always confuses me. I have seen people using one, two, three four slashes together.

I am on fr 0.16.1.1-signed on palemoon 27.9.2-64 bit

Thanks.
-- 
Rawat

**Comment by vsrawat** [comment]
on the other hand, I had input having (s) denoting optional singular plural of the word,
sample (s)	sample(s)
joint (s)	joint(s)
separated by space, that space I didn't want in between, because that makes google translate take (s) as a standalone entery,
so I had removed space by escaping () to take it literally with this code

`{"input":   "([a-z]) \\(s\\)", "inputType": "regexp",   "output": "$1(s)", "caseSensitive": false},`

and it is working.

so, now it is clear that \\( in json file makes fr taked ( literally.

Is that correct, or am I still missing something.

Thanks.

**Comment by vsrawat** [comment]
on the other hand, I had input having (s) denoting optional singular plural of the word,
sample (s)	sample(s)
joint (s)	joint(s)
separated by space, that space I didn't want in between, because that makes google translate take (s) as a standalone entery,
so I had removed space by escaping () to take it literally with this code

`{"input":   "([a-z]) \\(s\\)", "inputType": "regexp",   "output": "$1(s)", "caseSensitive": false},`

and it is working.

so, now it is clear that \\( in json file makes fr taked ( literally.

Is that correct, or am I still missing something.

Thanks.

**Comment by vsrawat** [comment]
mea culpa
it was not at all about escaping parenthesis,
it was about mg and ml, getting combined as m(gl)

As only one of those has to come, it should have [],
so m(gl) was what was wrong. 
making it m([gl]) without any slashes makes it work.

Please close this thread.
Thanks.

**Comment by MeilEsdelhi** [comment]
@vsrawat 
Does it work for you now?

I ask because: it would be great to see, if regular expression on the "output" side would work.

@Woundorf Are there regexp rules the can be used on the side of the output? I thought not.

**Comment by Woundorf** [comment]
In the output you can use normal text and the special values `$&`, that represents the whole matched input, and `$1`, `$2`, etc., that represent the first, second, etc. matches in parentheses when you use regular expressions in the input.
