### ISSUE TITLE
Can't detect whitespaces in URLs with FoxReplace

### ISSUE THREAD

**Issue by McBobb** [Woundorf/foxreplace#288]
I've been looking all over online to find an answer, but there's nothing. It's probably just something simple I don't understand because RegEx makes absolutely no sense to me.

But anyway, I visit a site where people submit "obfuscated" URL (the text of the URL altered in some way so clicking doesn't directly open the link target)

FoxReplace has been great with dealing with that, so I can just right-click and open the URL in a new tab without having to bother with copying and editing the URL string.

Unfortunately, FoxReplace is absolutely failing to detect whitespaces inserted into URLs. I've tried everything I could think of to get it to recognize whitespaces in the "find" field, but nothing works.

I tried just entering the specific URL (at least the part that never changes for the URL, despite specific destination involved, with just blank spaces in them, in Text mode, Whole World mode and even in RegEx mode; nothing.

I tried replacing the blank spaces with [\b] in all three modes; nothing

I tried replacing the blank spaces with [%20] in all three modes; nothing

I tried looking up RegEx expressions for detecting whitespaces, but they're all gobbledygook to me.

The thing is, I'm not trying to find and replace whitespaces in any URLs; just a very specific domain's URL, and frankly, this seems to be way too difficult to do such a simple thing. The previous Text Replace Addon I used before the damned WebExtentions made everything a living hell could handle simple spaces in URLs that I wanted to remove from URLs.

Please, help!

**Comment by Woundorf** [comment]
Can you provide an example URL?

**Comment by McBobb** [comment]
For example, one person posted a manually-obfuscated URL that started with

```
https:// mega.nz/
#
```

I want to use FoxReplace to not only target the whitespace before "mega", as well as the carriage return before "#" so I can remove them, restoring it back to a working URL.

**Comment by Woundorf** [comment]
Have you tried with `\s`?

From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes:

> `\s`
> Matches a single white space character, including space, tab, form feed, line feed and other Unicode spaces. Equivalent to `[ \f\n\r\t\v\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]`. For example, `/\s\w*/` matches `" bar"` in `"foo bar"`.

**Comment by McBobb** [comment]
I tried \s, but it didn't work. I tried both: 

https://[\s]mega.nz/[\s]#

And

https://\s\mega.nz/\s\#

with no luck

**Comment by Woundorf** [comment]
Maybe with `https://\s*mega.nz/\s*#`? But if the carriage return is actually some HTML like `<br>` or a paragraph change, then you will need something more complex. You should check.

**Comment by SaltatorMortis** [comment]
can you post the to matching HTML of the specific site?(plz dont post the whole site :-D )
maybe they use whitespace lookalike letters(iE space in Braille)
without that its hard to provide a solution

**Comment by SaltatorMortis** [comment]
this is the simples blind "match all" regex i can come up with
this Regex has the possibility to run over html or string
maybe you need to adjust the match length [^#]{0,100}

here are 2 versions

insert;
```
(mega.nz\/)(?=[^#]{0,100}(#[^ \n<>]+))
 https://$1$2 
```
overwrite;
```
(https://)[^]{0,25}(mega.nz\/)[^#]{0,100}(#[^ \n<>&]+)
$1$2$3 
```


insert version;
```
https:// mega.nz/

#matchdre
```

```
https://  https://mega.nz/#matchdre
#matchdre
```

overwrite version;

```
 https:// mega.nz/
 
 #matchdre
```

`https://mega.nz/#matchdre`
