### ISSUE TITLE
Enable and disable automatic replace onload By code

### ISSUE THREAD

**Issue by mohamedmnari** [Woundorf/foxreplace#290]
I need to know what is the code of enabling and disabling the automatic replace , that would be great and helpful , what code should I write

**Comment by Woundorf** [comment]
I suppose that you mean how to do it if you modify the extension code.

For example to set it to true you can do `storage.setPrefs({ autoReplaceOnLoad: true });` (the `storage` object is defined in storage.js). Or you can also call directly `browser.storage.local.set({ autoReplaceOnLoad: true });`.

**Comment by mohamedmnari** [comment]
yes that what i was asking exactly ! thank you i will try it !

**Comment by mohamedmnari** [comment]
it worked ! thank you so much for answering our issues
