### ISSUE TITLE
is there a code to make automatic replace after page load (not onload)? and where is the part of foxreplace code where it finishes replacing the page?

### ISSUE THREAD

**Issue by mohamedmnari** [Woundorf/foxreplace#292]
I'm using foxreplace in one website. it's  one link actually;
rarely foxreplace doesn't perform (1% of the times), I don't want the page to show up if foxreplace didn't replace , in this case i thought if there is an auto replace onload and after load then this rare proplem will disappear .
or maybe instead of replacing after load again , i'm hiding a div so when foxreplace finishes replacing I will unhide the div (that means if foxreaplace didn't perfom the div will stay hidden) .. to do that i need to know where i can put my code to unhide the div when foxreplace finishes .

sorry if I made it seem complicated.

**Comment by Woundorf** [comment]
The first question is already answered in #295. The second one,

> where is the part of foxreplace code where it finishes replacing the page?

In scripts/content.js, just after each call to `replaceWindow()`:
- the first one is for automatic substitutions on load
- the second one is for substitutions done with the replace sidebar
- the third one is for manual substitutions applied from the toolbar button ("Apply manual substitutions")
- the fourth one is for automatic substitutions applied every _n_ seconds
