### ISSUE TITLE
what if I want the Url of data updates every 1sec not every minute ? what would be the code of that ? or any way to make it update in less than 1min

### ISSUE THREAD

**Issue by mohamedmnari** [Woundorf/foxreplace#293]
I need the url to Periodically updates every 1sec , I need the code of doing this , or any other way just to make it update in less than 1min

**Comment by mohamedmnari** [comment]
and how to check by code if the "Periodically update from URL" is enabled or disabled

**Comment by Woundorf** [comment]
It uses [browser.alarms.create()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/alarms/create) which only accepts a period in minutes. Look at scripts/subscription.js, start() method. However, you can try to set a fractional value and see if it works (I don't know). Similar to the other issue, you can do `storage.setPrefs({ subscriptionPeriod: 1/60 });`, or directly `browser.storage.local.set({ subscriptionPeriod: 1/60 });`.

To check if it is enabled or disabled you have to read the enableSubscription value: `storage.getPrefs().then(prefs => { if (prefs.enableSubscription) ... });`. This is done in scripts/background.js.
