### ISSUE TITLE
how can I call the function that replaces the specified data?

### ISSUE THREAD

**Issue by mohamedmnari** [Woundorf/foxreplace#295]
I want to do the replacements in a specific time between my code , is there a function to call ? if not is there a code to write instead ?

example : 
setTimeout(function(){
//replace the data <---- that what i need
},5000);

**Comment by Woundorf** [comment]
If this is already a content script, take a look at the switch in content.js; all three cases follow the same pattern to call `replaceWindow`.

Otherwise, it is a little more complex. You have to send a message to the content script like it's done in background.js, in the function `replaceCurrentTab`.

**Comment by mohamedmnari** [comment]
thanks ! can you write me the line to call "replaceWindow" . please

**Comment by Woundorf** [comment]
```
storage.getPrefs().then(prefs => {
  if (prefs.autoReplaceOnLoad) {
    storage.getAutomaticGroups().then(list => {
      replaceWindow(window, list, prefs);
    });
  }
});
```

**Comment by mohamedmnari** [comment]
because sometimes it fails to replace in my situation and i want to wake it up and force it .. that is why i need to call the function from my code

**Comment by Woundorf** [comment]
Yes, just put that in your timeout function and it shoud work.

**Comment by mohamedmnari** [comment]
What about the data in options table ?

**Comment by Woundorf** [comment]
It is returned in `storage.getAutomaticGroups()` (the `list` in the lambda).
