### ISSUE TITLE
What is the implications of format 0.15 to 2.1 change

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#296]
Today, after updating to new release, when I loaded my json files, I got a message to the effect that these files are old format 0.15 that will become supported in future, I should load version 2.1

What change is that? 
Where can I get information on version 2.1?

As the older version is still running, 
1. does it mean that newer version is not yet applied and we can't load 2.1 version files till that is implemented?
2. or does it mean that currently both 0.15 as well as 2.1 versions are working and we can change  our files to newer version and load immediately?

Thanks.
newer version

**Comment by Woundorf** [comment]
I just added a version check in the latest version thinking about users that keep lists in older formats for a long time (like you in this case). That message means that this format is still supported but it is not the latest one and thus support for it may be removed in some future version if it becomes too hard to maintain.

You can just export the list after importing a file and it will be saved with the latest format (2.1 at this moment). The difference is a new field for each group called "mode". As explained in the changelog:

Added 3 modes for substitution groups (#206):
- auto: used in auto-replace on load and auto-replace every n seconds
- manual: used when manually applying the substitution list
- auto&manual (default): used in both cases, equivalent to previous versions

I don't remember if you are the user that generates lists with a spreadsheet, if that's the case then you should update it to add that field.

**Comment by vsrawat** [comment]
Yes, Marc,

You identified me correctly.

I will figure out the placement of this MODE, and its contents, and 
modify my spreadsheet columns and formula to get it correct.

I have to use four browsers ff, palemoon, Light and Basilix to convert 
my different types of input data using fr.  Now, only ff will follow 
this new format, while other three (palemoon, Light and Basilix) are 
still using using older foxreplace. E.g. palemoon is stuck on 
foxreplace-0.16.1-fx and later releases don't work, and if I update 
palemoon to later versions then foxreplace doesn't appear there.

So, I have to keep older formats for those three browsers.

Gladly, my data sets are totally different for all 4 browsers, so I can 
use new format in ff set, and continue with old format in data for other 
three browsers. So, that is ok.

Just that I will have to manage both the formats simultaneously and I 
will have to make a mental note remembering this all the time.

Thanks.
-- 
Rawat

**Comment by vsrawat** [comment]
exported json file from fr.

Found the only change in previous version and exported version is
second last line
       "mode": "auto&manual"

as in
           "caseSensitive": false
         }
       ],
       "html": "none",
       "enabled": false,
       "mode": "auto&manual"
     },

1. Please confirm if this is the only change in previous and newer versions?

2. What If I put this change in files of earlier versions also?
I mean will fr (earlier releases of fr) not import such files and will 
throw an error,
or will fr still import and will just ignore the "mode" line, or will 
import and keep it but will not use it?

Thanks
-- 
Rawat

**Comment by vsrawat** [comment]
By adding
 >        "mode": "manual"
it gave an error about missing , or something, so I had to add a , at 
the end of line before this addition so that it became

 >        "html": "none",
 >        "enabled": false,
 >        "mode": "manual"
 >      },

That comma warning disappeared, but it was still giving older version 
warning, so I checked the json file and found that first line proudly 
announcing that it was "version": "0.15",

so I changed that to "version": "2.1",

And then all warnings disappeared and I seem to have successfully 
migrated to 2.1

A summary for other users:

1. change top line from "version": "0.15", to "version": "2.1",

2. put a , at the end of line "enabled": false so that it looks 
"enabled": false,

3. After the above line, add a line "mode": "manual"
(or "mode": "auto&manual" or "mode": "auto" as you want as per your 
requirement)

save the file.

That is it. This file has migrated to higher version and will work.

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment]
Sorry for the delayed response.

> 1. Please confirm if this is the only change in previous and newer versions?

Yes, it's the only change.

> 2. What If I put this change in files of earlier versions also? I mean will fr (earlier releases of fr) not import such files and will throw an error, or will fr still import and will just ignore the "mode" line, or will import and keep it but will not use it?

It would be ignored.
