### ISSUE TITLE
What is the implication of "Updated XRegExp to version 4.2.4"

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#297]
I read in the change notes that "Updated XRegExp to version 4.2.4"

What is the implication of this change for existing fr users.

What modifications are we supposed to make in our regex-es?

Thanks.

**Comment by SaltatorMortis** [comment]
for you it changes nothing, its just a backend change.
the used syntax is the native JS regex and not the syntax used by xRegExp

**Comment by vsrawat** [comment]
Thanks for assuring.

-- 
Rawat

**Comment by Woundorf** [comment]
Just what @SaltatorMortis said.
