### ISSUE TITLE
mozilla addons site removed pre-WebExtension versions of fr, Where to find the same?

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#298]
Mozilla firefox addons site is now showing only WebExtension versions of fr, viz. v2.0.0 to v2.3.1. It has somehow removed pre-WebExtension versions, 

As I am using earlier versions of fr on palemoon, Firefox light and Basilix browsers, and they are working well though not officially supported by you,

Where can I find older pre-WebExtension versions of fr to download from?

btw, how can Mozilla firefox addons site remove earlier versions, as it is theoretically possible for any ff user to continue using earlier firefox pre-WebExtension versions so he would need supporting version of foxreplace do download and use?

Thanks.

**Comment by SaltatorMortis** [comment]
my goto for legacy Addons is the Site legacycollector.org
in your case look for https://legacycollector.org/firefox-addons/6510/index.html

**Comment by vsrawat** [comment]
ok. thanks.

Good site. I have even bookmarked it for other requirements.

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment]
Earlier versions have not been removed from the server, I can still download the xpis from my account, but it is impossible for anyone else.

If that other site disappears some day you could also generate your own xpi by downloading the source from a [specific release](https://github.com/Woundorf/foxreplace/releases) and then running build.sh in Cygwin or Bash. Note that the generated xpi would be unsigned (I don't know if this is an issue for those other browsers).
