### ISSUE TITLE
Text on Multiple Lines

### ISSUE THREAD

**Issue by mordecai98** [Woundorf/foxreplace#302]
I'd like to set up a signature, but only seem to be able to do it on one line. Ideally, it would look something like this:

Best Regards,
John Smith,
CEO Smith Enterprises
Enterprising for Entrapaneurs since 1998

**Comment by Woundorf** [comment]
If it is HTML you can use `<br>` to create newlines. If it is plain text you can use `\n`.

**Comment by mordecai98** [comment]
Fabulous! Thanks much!
