### ISSUE TITLE
Two paragraphs replace

### ISSUE THREAD

**Issue by BaltoDog** [Woundorf/foxreplace#304]
Hello,

first of all, congrats for this amazing plugin!

Sometimes, I need to replace a text which is like that:

**_I need to rep
lace this_**

Unfortunately, being this text split into two paragraphs it is impossible to replace the text with something else with just one action right now. 

Is it possible to allow this in situations like that, so that replacing "I need to rep lace this" will replace both paragraphs with whatever I want, using just one paragraph? The normal browser search function will already find text split into two paragraphs separated by a normal space, so it would be great to implement this into the plugin as well.

Thank you!

**Comment by Woundorf** [comment]
If the text is plain text, without HTML, you can match the line break if you use regular expressions with `\n`. If it is in HTML it is more complicated: you have to see what code there is in between; it may be a `<br>` or `</p> <p>` maybe with spaces in between.
