### ISSUE TITLE
Substitution is not executed on a script

### ISSUE THREAD

**Issue by cesco1985** [Woundorf/foxreplace#307]
Good morning everyone, 
I had a problem. I choose to substitute a phrase, but Nothing happens. I think it is due to the fact that the phrase appears later, from a script. I try to be more precise:

I have chosen to substitute a phrase: 
![sosti](https://user-images.githubusercontent.com/38474359/74082349-52357000-4a59-11ea-90e6-e2cdf461c4dd.PNG)

"Attenzione alle false telefonate" with "non rispondete alle false telefonate"
Then I go on the site https://www.unicredit.it/it/privati.html and I click "Accesso all'area clienti" (on the right, at the top of the page) and it appears the phrase I want to substitute. 
I don't know what is the problem (maybe it is a jQuery), but if i click on the phrase and choose to manually substitute everything is fine, but I don't need this. I want anything is ok at the beginning.
Thank you

**Comment by Woundorf** [comment]
You are right, that part appears from a script, thus this is the same as #13 which is unfortunately not implemented yet. You can maybe try the "Apply automatic substitutions every n seconds" option to see if it suffices you as a workaround.
