### ISSUE TITLE
Can I use FoxReplace in a single field, or on just selected text, instead of on the whole page?

### ISSUE THREAD

**Issue by PartyRambo** [Woundorf/foxreplace#308]
I love this tool, and use it regularly.
But I have not found a way to apply FR to just a field on a page, or just the selected text.

I'm opening web pages in edit mode, where I'm able to modify a dozen fields.
But there are a few fields I do NOT want modified by a whole-page replacement.
That is, certain fields will have different FR rules applied to them.

My overall macro runs FR, then goes to certain fields, selects their text and reverses FR's replacements, using other tools.
If there's a way to only apply FR to (a field) or (selected text), how?!?
If not, could this be integrated?

i.e. with cursor in a field, only replace that field; OR
with a cursor selecting text, only replace within that text

For my project, this is the most useful tool I have, but this would be a tremendous improvement if possible.
Thanks!

**Comment by Woundorf** [comment]
Sorry for the late response, I received the notification but it seems I forgot about it then.

I have started work on #56, which would allow you to select specific items to replace by way of CSS selectors or XPath. To apply only on selected text is requested in #121 but I haven't started it.

I'm going to close this as duplicated and you can follow those other two issues if you want.
