### ISSUE TITLE
Foxreplace breaks otomoto.pl when rule use HTML: Input & Output

### ISSUE THREAD

**Issue by cra3yk** [Woundorf/foxreplace#310]
Hi

There is polish buy/sell cars site (otomoto.pl) which use [# with parameters in the end of url links](https://i.imgur.com/EV6KoJO.png)

For example enter:
https://www.otomoto.pl/osobowe/seg-cabrio/od-1996/

and click any car ad. Link/URL will look like this example:
https://www.otomoto.pl/oferta/opel-astra-opc-parktronik-109tys-km-ID6Dm6rR.html#c85fb33507

and I want to get rid of the "**#c85fb33507**" reminder (the alphanumeric reminder will be different for different search attempts)

So I created this rule (HTML: Input & Output enabled)
```
URLs: https://www.otomoto.pl/osobowe/*
```

Substitutions:
```
Replace:  (oferta\/[\w-]{1,140}ID6\w{1,10}\.html)(#\w{1,12})
Type: Regex
With:  $1
```

which works (manually applied), but breaks top of [this site content:](https://i.imgur.com/TN2l5sl.png)

So I disabled my rule and I created seconed one - simple text replace rule (for example): Replace name "Opel" with "Lepo" (with HTML: Input & Output enabled) and when manually applied - also break this site (unable to choose different car maker etc.)

Could You look at this issue?

**Comment by Woundorf** [comment]
Hi, if you only want to replace links you could use "HTML: None" and check the "Replace URLs" checkbox in the options. That way I think nothing should break with your current substitution.

**Comment by cra3yk** [comment]
Hi

With "HTML: None" - not works at all.

You could reproduce this using CTRL+SHIFT+F9 and [paste my rule](https://i.imgur.com/TuwUj4R.png)

**Comment by Woundorf** [comment]
I have tried it and the fragment parts are removed with your rule and HTML none. Have you enabled "Replace URLs" in the options?

**Comment by cra3yk** [comment]
Eureka!

I have found my mistake. I've tried with (and without) "Replace URLs", but only "HTML: Input & Output" and "HTML: Output only".

I haven't tried "HTML: No" with "Replace URLs", which ..... works well! (for me this was totally unexpected)

**Comment by Woundorf** [comment]
If this was unexpected maybe I need to improve the documentation. But it should definitely become a group option in the future.

Anyway I'm glad your problem is solved.
