### ISSUE TITLE
[Suggestion] Add a list of websites where FoxReplace is deactivated

### ISSUE THREAD

**Issue by Helgifder** [Woundorf/foxreplace#316]
Could you add a way to add a list of websites where FoxReplace would be deactivated? It would be useful for working on websites like Wikpedia where if you edit anything on the page, all the words FoxReplace replaces are replaced by their replacements.

**Comment by Woundorf** [comment]
You already have it: in the URLs section, if you put an URL starting with `-` it means that the list does not apply there (the URL is rendered in red to indicate this). E.g. if you add the URL `-wikipedia.org` the substitutions in that group won't be applied in any Wikipedia page.
