### ISSUE TITLE
Fox replace is not allowing lists or URL detection. 

### ISSUE THREAD

**Issue by roguewavelimited** [Woundorf/foxreplace#318]
I just added foxreplace to my Mac Firefox.  The only configuration I see that I can do is a simple "Replace" - "With" dialog in the Firefox sidebar.  And any thing you enter there is only good for the presently displayed page.

How do I add lists, etc???

**Comment by Woundorf** [comment]
You can do that in the options. You can open them from the toolbar button.

**Comment by roguewavelimited** [comment]
Thank you.  I didn't notice the button - kind of dim.

Rick
