### ISSUE TITLE
Enh Request 

### ISSUE THREAD

**Issue by janpernik** [Woundorf/foxreplace#320]
For regular expression search would be nice to have option to use placeholder in replacement string like & for whole string, \1 \2 for groups.
Thnx
Jan

**Comment by Woundorf** [comment]
This is already available: you can use `$&` for whole string and `$1`, `$2`, etc. for groups. All the special patterns listed [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_a_parameter) should work.
