### ISSUE TITLE
Not Working At All in FF 92.0.1

### ISSUE THREAD

**Issue by sqgl2** [Woundorf/foxreplace#325]
Does not appear in my FF Tools pull-down menu anymore. 

My replacements are being ignored.

CTRL-SHIFT-A reveals the plug in is installed and activated though.

FR v2.4.0, Windows 7

**Comment by Woundorf** [comment]
I have tried in different configurations of Firefox 92.0 and newer on Linux and Windows 7 and it works for me.

**Comment by sqgl2** [comment]
Looks like it is not an FR problem. _All_ of my plugins have disappeared from the toolbar, not just FR. I have the FR options bookmarked and it does not work: moz-extension://df82dc29-b603-4480-ad49-be534aa814b3/options/options.html

**Comment by sqgl2** [comment]
Looks like it is not an FR problem. _All_ of my plugins have disappeared from the toolbar, not just FR. I have the FR options bookmarked and it does not work: moz-extension://df82dc29-b603-4480-ad49-be534aa814b3/options/options.html
