### ISSUE TITLE
Substitutions work only on active tab

### ISSUE THREAD

**Issue by Mattia2510MC** [Woundorf/foxreplace#336]
I have a two monitor setup and I keep the tab that needs FoxReplace on the second monitor. The automatic substitution works only when the tab is active (only when I click on said tab FoxReplace works). I mainly work on the first monitor, so the tab on the second monitor is never active.
Could you add an option to make FoxReplace work on all open tab, not only the active/loaded one?

**Comment by Mattia2510MC** [comment]
Ok found the problem.
In _foxreplace/scripts/background.js_ you wrote
> function replaceCurrentTab(aMessage) {
>   browser.tabs.query({
>     currentWindow: true,
>     active: true
>   }).then(tabs => {
>     if (tabs[0]) browser.tabs.sendMessage(tabs[0].id, aMessage);
>   });
> }

Would it be possible to add an option to make the script run on all **visible** tabs or directly on all open tabs?

**Comment by Mattia2510MC** [comment]
Yes, I need period substitutions to work on a tab that is open on a second screen. This page is dynamically updated so _apply substitutions on page load_ doesn't work

**Comment by Woundorf** [comment]
OK, I can modify this to apply to all visible tabs in case of periodic substitutions.

**Comment by Mattia2510MC** [comment]
Not to be rude, but is there an ETA for this fix?
This extension is crucial to me and that's the only thing missing

**Comment by Woundorf** [comment]
I have already done it and released a new version.
