### ISSUE TITLE
fox replace works on page, but not the comment section (bug?)

### ISSUE THREAD

**Issue by wtfiwinomgs** [Woundorf/foxreplace#341]
have several link, take this one for example:
https://nypost.com/2023/01/09/tennessee-cops-married-female-officer-fired-after-repeated-wild-sex-romps/

fox replace will work on the article itself, but once it hits comment section it does not work unsure why.

**Comment by Woundorf** [comment]
Sorry for the late answer. I don't know the exact reason but I see that the comments are inside a custom element (`<ow-hoabqnshfjc>`). This is probably related to the issue.
