### ISSUE TITLE
Regular expressionss with matching groups

### ISSUE THREAD

**Issue by Eidonko** [Woundorf/foxreplace#349]
Dear Sir,
I wanted to filter the contents of a web page such that strings like "Figure 31 42" would be changed into "Figure 31" (thus, skipping the second number)
I have tried to apply the following regex: (Figure)([ ])([0-9]*)([ ])([0-9]*) and specified to change it with "Figure \3", where "\3" would be the third matching group.
Regrettably the text was changed into "Figure \3", that is, the \3 was not interpreted as a matching group.
Would it be possible to apply regex with matching groups? Thank you very much!
Kind regards,
eidon

**Comment by Woundorf** [comment]
Hi, sorry for the late reply. You need to use the JavaScript conventions, and thus use `$3` instead of `\3`.

**Comment by Eidonko** [comment]
Oh I see! Thank you very much! 

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Jul 5, 2023, 12:45 by ***@***.***:
