### ISSUE TITLE
Adding Colors to Changes

### ISSUE THREAD

**Issue by I7y3o1** [Woundorf/foxreplace#353]
Working on certain platforms, we see a large amount of information. And the words that we change are not always evident. Is it possible to make an additional filter so that the changed words are highlighted in the color you are interested in? For example, just the whole word or sentence was highlighted in color

**Comment by Woundorf** [comment]
Hi, you can do it already if you use HTML in output to add a wrapper to add color. For example:

Replace: color
Type: Text
With: `<span style="background-color:yellow">$&</span>`
HTML: Output only

Result when applied to this page:

![imatge](https://github.com/Woundorf/foxreplace/assets/1915151/5b90cf84-ec74-4954-8372-3c773f972cb5)

**Comment by I7y3o1** [comment]
but in this case we offer the old word. And how to change the new one and highlight it?

**Comment by Woundorf** [comment]
Then use `<span style="background-color:yellow">new word</span>` instead.

**Comment by I7y3o1** [comment]
thanks
