### ISSUE TITLE
Keyboard shortcuts no longer work with 2.6.0

### ISSUE THREAD

**Issue by dcunhas** [Woundorf/foxreplace#354]
After the new version 2.6.0 update, the keyboard shortcuts (Ctrl+F9, Ctrl+Shift+F9) no do anything. I have confirmed that they are still set in the Firefox Manage Extension Shortcuts page, and clicking the buttons in the extension menu still work.

**Comment by Woundorf** [comment]
I have reproduced the problem but it works after restarting Firefox. Can you confirm?

**Comment by dcunhas** [comment]
I'm not sure why, but restarting Firefox didn't work for me. Restarting my computer did fix things though. Maybe Firefox didn't close fully or something? Anyway, the issue seems to be resolved.
