### ISSUE TITLE
Is it possible to delete a line ?

### ISSUE THREAD

**Issue by benintech** [Woundorf/foxreplace#364]
I'm trying to delete all lines having only `sometext` on it.

But if I replace `sometext` with nothing, it replaces the line an empty one.

Is it possible to delete the line instead ?

**Comment by Woundorf** [comment]
If it is HTML, you should set HTML mode to "Input & output" and include the `<p>` and `</p>` or the `<br>` in the substitution to also remove them. If it's some kind of plain text you can try to include a `\n` (newline) and setting the input type as regular expression.

**Comment by benintech** [comment]
Great, the `\n` trick did the job. Thanks.
