### ISSUE TITLE
Is it possible to handle TypeError:p2 is undefined and process conditional statements with Output type: Function?

### ISSUE THREAD

**Issue by iG8R** [Woundorf/foxreplace#371]
Hello.
I'm trying to use the Function output type, but I've run into a few complications.
1. When there is no group in the provided input, I get this error: TypeError:p2(group number) is undefined. How can I make it work like the Text output type where nothing is inserted when there is no group?
![image](https://github.com/Woundorf/foxreplace/assets/11407417/45a6be8f-38c6-465d-b70a-e10497e96382)
![image](https://github.com/Woundorf/foxreplace/assets/11407417/56ab5332-1c6c-4840-9308-35eae2875455)

2. Is there a way to use conditional statements in the Function output type?
![image](https://github.com/Woundorf/foxreplace/assets/11407417/dddbf1e6-728a-418a-8d35-231d45e22851)
![image](https://github.com/Woundorf/foxreplace/assets/11407417/2312250a-7576-4377-81be-7bb07a0e6323)
![image](https://github.com/Woundorf/foxreplace/assets/11407417/ac38ee2d-056f-45d7-ac60-8c8687a73505)
![image](https://github.com/Woundorf/foxreplace/assets/11407417/c456f400-0f3d-415c-8bfe-b0ad7103cd7c)

**Comment by Woundorf** [comment]
Both questions can be solved if you use [arrow function expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions). These will allow you to capture the already present parameters and implement any custom logic you want. The basic structure would be like this:

`(() => { /* Custom logic returning a value */ })()`

In summary, you define a function and then call it immediately.

For the first issue, in a custom function you can test if `p2` is defined and act accordingly.

**Comment by iG8R** [comment]
Thank you so much for such a quick and appropriate answer!

**Comment by Woundorf** [comment]
Thank you for your suggestions and bug reports. I don't know if they will be implemented but it's good to have the ideas.
