### ISSUE TITLE
Extension stopped working (manual substitutions)

### ISSUE THREAD

**Issue by githubeumpenico** [Woundorf/foxreplace#380]
Hello; 

I use FoxReplace daily for Manual Regex and Text substitutions (I have a whole .json file collection). 
Last time I used it was on Friday 11th October.
This morning, 14th, it stopped working for Manual substitutions. Tried different versions of Firefox, same result.

I use this to automatically format and correct text for editing a website. In the backoffice we have a text field to paste the text, edit and format it (selecting text, applying bold and italic keys, for example). 
Now, when using the extension, it replaces the text OUTSIDE the field (for example, any text belonging to the backoffice interface) matching the parameters - but nothing happens INSIDE the field, where it should (and did previously).
It did work inside the field before, up until this morning. Now, it doesn't.

Automatic substitutions on page load doesn't seem to be affected, but I can't use this function, since it will accumulate many replacements on top of one another, when I open the same article many times during work. This will destroy the formatting.

Firefox 131.0.2 (64 bits) snap on Ubuntu 24.04.1 LTS
Firefox-ESR 128.3.1esr (64 bits) .deb on Ubuntu 24.04.1 LTS

**Comment by Woundorf** [comment]
Could it be a change in that backoffice? From your description I guess that the text field must be a textarea and substitutions continue working in textareas (you can try it right here in the response field). Furthermore, both manual and automatic substitutions call the same functions internally, there is no reason for one to work and the other not if the content is the same. Thus, maybe the backoffice has changed and is doing some strange things with Javascript. You should try to investigate if that's the case.

**Comment by githubeumpenico** [comment]
Out of the blue it started working again, but no changes to backoffice were made before or after...this is super weird. Closing.
