### ISSUE TITLE
New feature request - apply to all except excluded url's

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Woundorf/foxreplace#92]
```
Currently, it seems you must have inclusion (allowed) url's for exclusion 
(disallowed) url's to work.

Would it be possible to only have exclusion url's, meaning text is replaced on 
all sites except those specified?

This would be really useful.

Thanks.
```

Original issue reported on code.google.com by `blingfla...@gmail.com` on 8 Nov 2012 at 4:55

**Comment by pennyplayer** [comment]
Is there still an ability to exclude URLs in the latest version? I couldn't find it

**Comment by Woundorf** [comment]
Yes, I see that now it's not explained anywhere, but to exclude an URL add it with a dash at the beginning, e.g. `-example.com`.

**Comment by 07416** [comment]
> Yes, I see that now it's not explained anywhere, but to exclude an URL add it with a dash at the beginning, e.g. `-example.com`.

Where the exclusion strings are added exactly?
